### ISSUE TITLE
Flare animation uses Linear curve on Flutter app, but the original file has a Cubic curve on it.

### ISSUE THREAD

**Issue by iamyogik** [2d-inc/Flare-Flutter#100]
My original Flare file/animation has a Cubic curve defined for all its animation. But when I export and run the same animation on my Flutter app, it seems to use a Linear curve. I have exported the files multiple times with different changes on it, but no luck.

I have attached both the design file and the exported file in the zip.

Flutter code:
`Scaffold(
      backgroundColor: Colors.white,
      body: Center(
        child: Container(
          child: FlareActor(
            "assets/flare.flr",
            animation: "animate",
          ),
        ),
      ),
    );`

Files: [flare_files.zip](https://github.com/2d-inc/Flare-Flutter/files/3266731/flare_files.zip)

Link to flare: [https://www.2dimensions.com/a/iamyogik/files/flare/new-file-4](https://www.2dimensions.com/a/iamyogik/files/flare/new-file-4)

Video of the flare animation running in the app: [https://drive.google.com/file/d/1B98DNE3Zq26jQs4YCsDx-2gYnNaPIo4J/view?usp=sharing](https://drive.google.com/file/d/1B98DNE3Zq26jQs4YCsDx-2gYnNaPIo4J/view?usp=sharing)

**Comment by umberto-sonnino** [comment]
Thanks for your report, we might've caught the issue, and there should be a fix out soon!
