### ISSUE TITLE
Flare animation not right in Flutter

### ISSUE THREAD

**Issue by jaumard** [2d-inc/Flare-Flutter#107]
I've made a simple audio wave animation (https://www.2dimensions.com/a/jaumard/files/flare/audiowave). 

But once exported and used on my app, it looks weird, only the central stick is visible but the corner radius is wrong, the two other are not visible at all. 

here is a quick video: 
[flareProblem.mov.zip](https://github.com/2d-inc/Flare-Flutter/files/3311568/flareProblem.mov.zip)

I'm using flutter stable and flare_flutter: 1.5.1

**Comment by luigi-rosso** [comment]
Should be fixed in 1.5.2!

**Comment by jaumard** [comment]
It's indeed all good in 1.5.2 ! Thanks for the quick fix ! :D
