### ISSUE TITLE
Loading Flare actors in advance

### ISSUE THREAD

**Issue by stx** [2d-inc/Flare-Flutter#110]
Hi there,

I'm seeing an empty/blank space load delay when even tiny FlareActor files are loaded and I need them to be visible immediately upon a screen load. Is it possible to preload these assets prior to runApp() or using some other strategy?

Thanks for your great work on Flare!

**Comment by luigi-rosso** [comment]
Hi @stx, this is how we did it in the developer_quest app:
https://github.com/2d-inc/developer_quest/blob/master/lib/src/widgets/flare/warmup_flare.dart

Basically one file that defines the files you want to preload and exposes a method to do so.

Then in your main you can call this directly before runApp:
```
warmupFlare();
```

**Comment by stx** [comment]
@luigi-rosso Brilliant! Thanks so much!

**Comment by stx** [comment]
I found that you can speed up load times surprisingly significantly by caching the assets in parallel. I'm seeing a ~40% improvement with just a few files.

```
Iterable<String> assets = ['path/to/file', 'path/to/file', ...];
Iterable<Future<FlareCacheAsset>> futures = assets.map((String asset) => cachedActor(rootBundle, asset)).toList();
await Future.wait(futures);
```

**Comment by luigi-rosso** [comment]
Oh great, thanks! I forgot to mention, you can also tell the cache to not prune:
FlareCache.doesPrune = false;

I wouldn't do this in projects that load an enormous amount of Flare files (or download a lot of them), but if you have small set, this helps keep them in cache.

We've been working on some new features in the embedding branch (which unfortunately isn't compatible yet) which brings down the load even further times and reduces jank while loading as even the smaller operations are pushed to an isolate. We might merge some of those improvements into master if we end up being too far off from getting that whole branch merged.

**Comment by stx** [comment]
Great! Thanks! What triggers pruning?

**Comment by luigi-rosso** [comment]
It happens whenever a flare file is no longer referenced. FlareActor will reference count the Flare files it loads:
https://github.com/2d-inc/Flare-Flutter/blob/0230aab0c7802c611085d505ee9ae9988e077558/flare_flutter/lib/flare_render_box.dart#L243

And then dereference them when they are no longer used (widget is detached or source is changed):
https://github.com/2d-inc/Flare-Flutter/blob/0230aab0c7802c611085d505ee9ae9988e077558/flare_flutter/lib/flare_render_box.dart#L223

The cache gets pruned 2 seconds after the asset is no longer referenced:
https://github.com/2d-inc/Flare-Flutter/blob/0230aab0c7802c611085d505ee9ae9988e077558/flare_flutter/lib/flare_cache.dart#L12
