### ISSUE TITLE
Issues when trying to load my animation 

### ISSUE THREAD

**Issue by barfomellow** [2d-inc/Flare-Flutter#118]
I have an error  when using FlareActor. Unhandled exception  in FlutterActorShape.initializeGraphics
It's only one of the files have this problem, other ones are loading good. Any idea what can be the problem? I have this error even when removing  all animations from the file. 
Im using   flare_flutter: ^1.5.2

Container(
        width: MediaQuery.of(context).size.width, 
        height: 100, 
        child: 
        FlareActor(
          'assets/New File(14).flr', alignment: Alignment.center, fit: BoxFit.contain)
)

StackTrace:

[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 6941): NoSuchMethodError: The getter 'iterator' was called on null.
E/flutter ( 6941): Receiver: null
E/flutter ( 6941): Tried calling: iterator
E/flutter ( 6941): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 6941): #1      FlutterActorShape.initializeGraphics (package:flare_flutter/flare.dart:177:34)
E/flutter ( 6941): #2      ActorArtboard.initializeGraphics (package:flare_dart/actor_artboard.dart:572:16)
E/flutter ( 6941): #3      FlareActorRenderObject.load.<anonymous closure> (package:flare_flutter/flare_actor.dart:224:16)
E/flutter ( 6941): #4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter ( 6941): #5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 6941): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 6941): #7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 6941): #8      Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 6941): #9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 6941): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 6941): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 6941): #12     FlareRenderBox.loadFlare (package:flare_flutter/flare_render_box.dart)
E/flutter ( 6941): <asynchronous suspension>
E/flutter ( 6941): #13     FlareActorRenderObject.load (package:flare_flutter/flare_actor.dart:218:5)
E/flutter ( 6941): #14     FlareActorRenderObject.filename= (package:flare_flutter/flare_actor.dart:209:5)
E/flutter ( 6941): #15     FlareActor.updateRenderObject (package:flare_flutter/flare_actor.dart:61:9)
E/flutter ( 6941): #16     RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4510:12)
E/flutter ( 6941): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
E/flutter ( 6941): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 6941): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 6941): #22     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
E/flutter ( 6941): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #24     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
E/flutter ( 6941): #25     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
E/flutter ( 6941): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 6941): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 6941): #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 6941): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 6941): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 6941): #33     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 6941): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
E/flutter ( 6941): #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
E/flutter ( 6941): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 6941): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 6941): #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter ( 6941): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 6941): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 6941): #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 6941): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 6941): #46     ComponentElement.performReb

**Comment by nitneuq33** [comment]
same issue, I have a previous project who work great and today I would try to rework this projet, and when I load the modify project I have the same issue ... So I back up to return to the working project but, now I can't do work this project ...

**Comment by luigi-rosso** [comment]
I see the problem. Odd that it wasn't giving you problems before, did you update the Flare file at all or is this with the same exact Flare files? I'll have a fix soon.

**Comment by nitneuq33** [comment]
It's the same file.Just rework=>try=>fail=>backup. Only change is version
package I've update between last work and my test today.

Le sam. 6 juil. 2019 à 19:26, Luigi Rosso <notifications@github.com> a
écrit :

**Comment by luigi-rosso** [comment]
I've published a new version to pub. Could you try version 1.5.3 and let me know if it fixes it for you?
```
flare_flutter: ^1.5.3
```

**Comment by nitneuq33** [comment]
It's ok, thank you :)

Le sam. 6 juil. 2019 à 20:14, Luigi Rosso <notifications@github.com> a
écrit :

**Comment by barfomellow** [comment]
Thank you, I will try the new version !

**Comment by luigi-rosso** [comment]
Great, I'm closing the issue for now, feel free to re-open if you still see a problem here.
