### ISSUE TITLE
Initial loading: image/flare not visible

### ISSUE THREAD

**Issue by YAPPDEF** [2d-inc/Flare-Flutter#124]
We had to upgrade flare_flutter from version `1.3.13` to `1.5.4`

With this newest version, all the flare animations are not shown initially. After some seconds, they are visible. But it looks really strange and we cannot go live like that.

**Comment by luigi-rosso** [comment]
The latest versions of Flare do load files asynchronously to prevent blocking the UI when waiting for the Flare file to load. I’m surprised it’s taking multiple seconds, unless you are using particularly complex Flare files. Could you share a file and maybe an example of how you are displaying it?

Also, are you testing on a physical device? If so, make sure to try it in release mode as the loading is significantly faster with AOT compilation.

**Comment by YAPPDEF** [comment]
Thanks for the fast response (as usual 👍 ) #kudos 

In release mode it's better, thanks. 
Would it be possible to display the image from the design preview as long as the Flare is loaded?
