### ISSUE TITLE
The animation of the sample project on Android shows an exception

### ISSUE THREAD

**Issue by koudle** [2d-inc/Flare-Flutter#13]
## step to reproduce
run example project with Android

## device

1. Android emulator

2. HUAWEI MATE 10（Other devices are not debugged）

![flare](https://user-images.githubusercontent.com/13464904/49842309-f7bd6700-fdf5-11e8-93a1-c213066b84d7.gif)

## exception
Android shows an exception
iOS shows ok

**Comment by luigi-rosso** [comment]
This is a duplicate of #12. We need to report this up the chain to the Flutter and SKIA team. I'm preparing a submission for that which I hope to send today. Thanks for reporting.

**Comment by koudle** [comment]
a duplicate of #12
