### ISSUE TITLE
 Int32List issue

### ISSUE THREAD

**Issue by nitneuq33** [2d-inc/Flare-Flutter#131]
I try to upgrade flutter to 1.7.8, but I found an issue not related with flare package, so I try to downgrade flutter to 1.5.4  and downgrad flare package to 1.5.3 who worked before, and now I have : 

```
Compiler message:
file:///C:/Users/utilisateur/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.4/lib/flare.dart:1027:18: Error: The argument type 'Uint16List' can't be assigned to the parameter type 'Int32List'.
 - 'Uint16List' is from 'dart:typed_data'.
 - 'Int32List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Int32List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^

```

**Comment by luigi-rosso** [comment]
If you're using Flutter 1.7.8, you should upgrade to the latest Flare (1.5.4). More details: https://github.com/2d-inc/Flare-Flutter/issues/126#issuecomment-511609969

**Comment by nitneuq33** [comment]
I have all reinstall it's ok now

**Comment by luigi-rosso** [comment]
Sounds good!
