### ISSUE TITLE
'Int32List' can't be assigned to the parameter type 'Uint16List'

### ISSUE THREAD

**Issue by SameerMasood** [2d-inc/Flare-Flutter#132]
Compiler message:
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.3.10/lib/flare.dart:981:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  smart_flare: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by umberto-sonnino** [comment]
Hey @SameerMasood this has been a common issue and is documented in the README [here](https://github.com/2d-inc/Flare-Flutter#flutter-channel).

Please make sure you're using the latest version of Flutter Stable. You can try running `flutter upgrade` or also `flutter channel stable` if you're on another channel.
