### ISSUE TITLE
Big problem while loading animation

### ISSUE THREAD

**Issue by Natanil** [2d-inc/Flare-Flutter#134]
I designed and implemented my animation in the flare workspace and it works fine but when i load the .flr file in my flutter app it throws a strange error. 
Here is my file : 
[list_walkthrough.flr.zip](https://github.com/2d-inc/Flare-Flutter/files/3464944/list_walkthrough.flr.zip)

The error is : 

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Unsupported operation: Result of truncating division is Infinity or NaN
#0      double._trunc_div (dart:core-patch/double.dart:44:57)
#1      double.~/ (dart:core-patch/double.dart:40:12)
#2      new Color.fromRGBO (dart:ui/painting.dart:139:32)
#3      FlutterColorFill.uiColor (package:flare_flutter/flare.dart:288:18)
#4      FlutterColorFill.update (package:flare_flutter/flare.dart:304:17)
#5      ActorArtboard.advance (package:flare_dart/actor_artboard.dart:285:21)
#6      FlareActorRenderObject._updateAnimation (package:flare_flutter/flare_actor.dart:413:19)
#7      FlareActorRenderObject._instanceArtboard (package:flare_flutter/flare_actor.dart:290:5)
#8      FlareActorRenderObject.load (package:flare_flutter/flare_actor.dart:304:5)
<asynchronous suspension>
#9      FlareActorRenderObject.filename= (package:flare_flutter/flare_actor.dart:263:5)
#10     FlareActor.createRenderObject (package:flare_flutter/flare_actor.dart:81:9)
#11     Render<…>

**Comment by luigi-rosso** [comment]
It looks like your opacity keyframes got exported incorrectly from Flare. Could you share a link to the file on 2Dimensions.com?

**Comment by Natanil** [comment]
> It looks like your opacity keyframes got exported incorrectly from Flare. Could you share a link to the file on 2Dimensions.com?

Thank you very much it got solved.
This is my file : 
[list_walkthrough (1).flr2d.zip](https://github.com/2d-inc/Flare-Flutter/files/3465933/list_walkthrough.1.flr2d.zip)
