### ISSUE TITLE
Design board exposed (probably) during animation transitions

### ISSUE THREAD

**Issue by yjoo9317** [2d-inc/Flare-Flutter#136]
Dear @luigi-rosso 

Recently I noticed that flare actor is often exposing design board right before playing animation.
The app dynamically changes animations between states and during the state transition,
we started seeing that happens.
Do you know any possible reason for me to see the design board?

Note:
I changed the version to 1.5.4 from 1.5.0 a week ago.
The reason I am putting this is that it seems like we didn't have this issue before.

Thanks.

**Comment by luigi-rosso** [comment]
Hey @yjoo9317, can you post a screenshot or video showing the issue? I'm not sure I'm following what you're seeing. Is it that you see the background color of the artboard?

**Comment by yjoo9317** [comment]
I cannot confirm exactly what it is.
But, at least I can tell that it showed the initial design assets of all animations in the flare file. 
Still, not enough...hmm,
If the flare animation has 2 animation sequences, then it (may) shows the overlapped initial frame of both animations.

**Comment by yjoo9317** [comment]
@luigi-rosso 
I forgot to mention something.
I wasn't able to use `sizeFromArtboard` property for my project.
Using that property, when the widget dynamically changes animation, it often showed that overlapped sequence.

Here is what I am going to do.
I will run same test with version 1.5.0 to see if it happens there.
1) If it doesn't, then there is regression in the flutter.
2) If it does as well, then.. I don't know.. any idea?
or Do I have to do something at `didUpdateWidget`?

Let me know. 
Thanks.

**Comment by yjoo9317** [comment]
HI @luigi-rosso
Our flare file contains two animations, thinking and progress bar.
 
Here is the thinking animation screen shot. 
<img width="307" alt="Screen Shot 2019-08-07 at 9 21 05 AM" src="https://user-images.githubusercontent.com/21015969/62639731-01e82480-b8f5-11e9-8885-b8c97a4d915a.png">

Here is the thinking animation shot with overlapped progress bar.
It seems to happen (possibly) when re-constructing the widget by update.
<img width="260" alt="Screen Shot 2019-08-07 at 9 21 16 AM" src="https://user-images.githubusercontent.com/21015969/62639773-1b896c00-b8f5-11e9-8b12-6e58524e35c1.png">

Right now, I check cachedActor and get the artboard, and only then I call setState.

If I start using `sizeFromArtboard` property then it happens more in a more dynamic situation. Also with that, from widget side, it has less control over or knows when.

**Comment by yjoo9317** [comment]
Hi @luigi-rosso,
I know you must be so busy with everything.
Do you have any thought on this issue? 

Thanks really.

**Comment by yjoo9317** [comment]
Hi @luigi-rosso 

I know you must be very busy with everything.
But I am still wondering whether you have any thought on that issue.
Let me know when you can.
Thanks Really.

**Comment by luigi-rosso** [comment]
Sorry, I haven't had time to dive into this in detail yet! I hope to find some time soon!

In the meantime, how are you mixing the two animations? Could it be that keyframes from one are not being reset by the other? It'd be really helpful if you could share code and/or a video of the problem to help me better understand what your intention is and where it's failing. It'd also be really helpful if you could share the Flare file with me. If it's private, you can download a backup and email it to me at luigi@2dimensions.com. 

Does it look any different in release/debug builds?

**Comment by yjoo9317** [comment]
Hi @luigi-rosso 

I didn't mix it. 
Flare showed the everything some how, that's why I thought it was a design board in the first place.
Not 100% sure.. Looks like if I run animation with `controller.isActive.value = false` then it just shows everything like that.
As such, during the transitions in my app, there is moment when the controller can be deactivated.

Does it ring any bell?

**Comment by luigi-rosso** [comment]
It's possible that a controller gets re-initialized if the widget gets detached and then re-attached.

This sounds really strange, almost like an animation from one file is being applied to a different file corrupting some of the shapes. If you get the chance, share both the code and the original Flare file so I can look in-depth at exactly what's going on...

**Comment by yjoo9317** [comment]
Hmm, it is one .flr file containing 2 different animations.

Since there could be copy right issue..
I am in the middle of something. 
Please give me some time to create a simple app that I can repro this.

**Comment by yjoo9317** [comment]
Hi, @luigi-rosso 

I sent a video clip.
Would you please verify if you received that? Thanks.
If you look at the video, you will see what I am talking about.
Whenever hero transition starts, it shows that symptom.

I haven't created the sample app yet, but the video was taken from my debug page for flare animations.

**Comment by yjoo9317** [comment]
@luigi-rosso 
Seems like I found the issue.
I didn't set animation name while creating actor since our custom flare controller controls animations and the animation is being loaded there.
But I notice if I don't set the animation name in creating flareactor, I have moment showing briefly every underlying animation on the same frame until it knows what to play.
Not sure, it should be addressed publicly. But that's what I had.
