### ISSUE TITLE
Animations List in runtime

### ISSUE THREAD

**Issue by nisimjoseph** [2d-inc/Flare-Flutter#138]
I want to get all animation list defined in the Flare file and that Flutter can run. 
for example, let's say I have 4 animations which supposed to be in the Flare file but one is missing, I can't find the API for this.
how can I know it missing or how can I know all the ones I can play?

**Comment by luigi-rosso** [comment]
I’m not at my desk right now, but look into some of our examples that use custom a FlareController. You can query the artboard for animations (either via artboard.getAnimation or access the full list via artboard.animations).

**Comment by luigi-rosso** [comment]
This article is a little more in-depth but it also discusses controllers: https://medium.com/2dimensions/building-an-interactive-login-screen-with-flare-flutter-749db628bb51

**Comment by nisimjoseph** [comment]
thank you.
