### ISSUE TITLE
Animation doesn't show in release

### ISSUE THREAD

**Issue by Fethi1** [2d-inc/Flare-Flutter#145]
i have made an animation on 2dimensions and i have use an image on it, when i run my app on debug everything works fine but when i  build the app and install it to my phone, the animation never show like the file doesn't exist at all even its space isn't reserved like it never existed.
any help!!

**Comment by umberto-sonnino** [comment]
Can you provide any more details? Flare File, Flare-Flutter version, your code?

**Comment by Fethi1** [comment]
alright just a second

**Comment by Fethi1** [comment]
flare file : https://www.2dimensions.com/a/Fethi/files/flare/balls
flare_flutter: ^1.5.7

code:
                GestureDetector(
                  onTap:count,
                                child: Container(
                                    height: height*0.45,                
                                    
                                    child:FlareActor('assets/animations/Balls.flr',alignment: Alignment.center, animation:animation,fit: BoxFit.contain,callback:(t){setState(() {
                                          animation = '';
                                    }); } ,) ?? Text('Animation'),
                                ),
                ),

**Comment by Fethi1** [comment]
the animation work as expected on debug mode but is doesn't show at all in release

**Comment by luigi-rosso** [comment]
Hey @Fethi1, sorry you're having trouble here. This sounds a lot like an issue we used to have with an older build of Flutter. Sorry for piling on more questions, but which Flutter version are you using? Could you try a different channel (stable, dev, master) to see if you see different results? We've tried on a few different devices here and cannot replicate the problem (we see it in release).

**Comment by Fethi1** [comment]
sorry for the late replay guys the problem wasn't related to Flare i was using a variable that stores the height of the device `MediaQuerry.of(context).size.height` and at release like it takes one more state refresh to be applied so it was always set to 0 that's why the animation never show up,i noticed this on a past project and i thought it would be solved after updates.
anyway thanks guys for everything you are doing a great job really.

**Comment by luigi-rosso** [comment]
Glad to hear you were able to fix this! I'm closing the issue for now, but please reopen if you think there's something we can help you with.
