### ISSUE TITLE
The getter 'iterator' was called on null

### ISSUE THREAD

**Issue by pblinux** [2d-inc/Flare-Flutter#146]
Hi. First, flare is so awesome and powerful, thank you for this tool.

I'm having troubles with my flare assets. My team create a character:
https://www.2dimensions.com/a/pixelagt/files/flare/josefina

But when I tried to load into a FlareActor widget, this exception appears:
```
I/flutter ( 7959): NoSuchMethodError: The getter 'iterator' was called on null.
I/flutter ( 7959): Receiver: null
I/flutter ( 7959): Tried calling: iterator
```
The versions I'm using:

flutter: v1.7.8+hotfix.4
flare_flutter: 1.5.7

We tried changing the targets to bones and re-ordering the structure but the error persist. Is this a bug or we are not doing it right with the flare files?

Thank you for your response.

**Comment by luigi-rosso** [comment]
Hi @pblinux, thanks for the nice message and thanks for reporting the bug. We just published a fix. Please update your pubspec to use ```flare_flutter: 1.5.8```.

**Comment by pblinux** [comment]
Thank you very much @luigi-rosso, now it's working.
