### ISSUE TITLE
Animation has a blank gap before completely loaded on low-end devices

### ISSUE THREAD

**Issue by TomassMaximum** [2d-inc/Flare-Flutter#151]
So, I have a little animation example( https://www.2dimensions.com/a/qingyun/files/flare/playing/preview ). It has a white background and some simple animated elements on top of it. The problem is, I guess because animation takes time for initializing, when the actor widget is built, it shows the white background at first, and some time later(around 1 second on iPad Mini2), the animated element shows up. This cause an unwanted behavior, which is a blank space showing for around 1 second on lower-end devices. 
I'm wondering is there any way to know when the actor is completely loaded, and show the widget after that.
Flutter version: beta v1.9.1
Flare version: 1.5.7
<img width="99" alt="Screenshot_2019-09-11 18 15 07_YW9T4i" src="https://user-images.githubusercontent.com/14291993/64690325-aea05d80-d4c2-11e9-81b2-02f6e8114891.png">

**Comment by luigi-rosso** [comment]
Hi @TomassMaximum, is the white rounded rectangle being drawn by your container/box decoration or is that also coming from the Flare file? I see it in your Flare file, but it's odd that it's just showing that and not the blue bars.

It might be related to caching. I have a test we can try for that. I don't recommend using this solution on projects that use a lot of Flare content as it will never release Flare files from cache, but it will help diagnose the problem. Try Strategy 1 from here:

https://github.com/2d-inc/Flare-Flutter/blob/sync_load/loading_strategies.md#strategy-1---warming-up-the-flare-cache

**Comment by TomassMaximum** [comment]
Ahh! I'm being stupid. Just forgot to remove the background from the widget(it was implemented by a rounded container at first). My bad, sorry...
