### ISSUE TITLE
flare animation doesnt scale right?

### ISSUE THREAD

**Issue by logemann** [2d-inc/Flare-Flutter#153]
Hi,

i am experimenting with different screen sizes and flare. Am i correct that a flare animation cant be scaled by using the normal flutter techniques like SizedBox and stuff?

Seems i need to provide different scaled animations (different flr files) and chose between them according to current user screenSize.

**Comment by lukepighetti** [comment]
`sizeFromArtboard` should be false and it should scale to fit its container. Did you try this yet or are you just asking before there's an issue?

**Comment by logemann** [comment]
Thanks for feedback so far. I am asking because its in fact a current issue and i tried some things in before my vacation two weeks ago. Give me another day or two to test your proposals.

**Comment by lukepighetti** [comment]
Examples would be helpful because by default FlareActor resizes its widgets to fit its parent.

**Comment by logemann** [comment]
Ok. Here we go. I got it so that it scales with the BoxFit parameter. But somehow i dont understand how it scales. 

See below the animation (when you wanna call it this way with a static image in this ticket system) with BoxFit.none and BoxFit.contain.

<img width="378" alt="Bildschirmfoto 2019-09-17 um 02 21 59" src="https://user-images.githubusercontent.com/346353/65002035-50c0ab00-d8f2-11e9-8e66-867685142788.png">

<img width="378" alt="Bildschirmfoto 2019-09-17 um 02 22 43" src="https://user-images.githubusercontent.com/346353/65002034-50281480-d8f2-11e9-8513-f9a207699988.png">

I dont get why the "BoxFit.contain" version is way smaller than it should be. Even more. The contained version will also scale down even if the animation fits perfectly on a bigger phone. 

So how do i get a result like "use the artboard size when it fits on the screen", otherwise scale down accordingly. But for this, just an enum like BoxFit.contain cant be enough to express that.

**Comment by lukepighetti** [comment]
Put it in a padded container with a maxWidth constraint?

**Comment by logemann** [comment]
i think i cant express my problem properly without having the full animation here in play.... will close this.

**Comment by umberto-sonnino** [comment]
Hey @logemann! 
The 2Dimensions team would love to help you with your issue, why don't you post a gif or a video?

**Comment by lukepighetti** [comment]
You can capture a video and post it as a gif

**Comment by logemann** [comment]
Thanks for reopening and showing love for your users, but i re-did the animation with a slightly different effect so that my previous issue is not there anymore. It for sure was no flare problem....
