### ISSUE TITLE
Play animation with controler

### ISSUE THREAD

**Issue by bedryck** [2d-inc/Flare-Flutter#161]
I play several animations at the same time using a controller. 
I did it using an example
![image](https://user-images.githubusercontent.com/22659468/65731928-52e3f000-e0d0-11e9-9826-97d08303ea8a.png)
![image](https://user-images.githubusercontent.com/22659468/65731993-8a529c80-e0d0-11e9-836c-4c4e011d16bb.png)
![image](https://user-images.githubusercontent.com/22659468/65732000-93436e00-e0d0-11e9-9464-9a7f676fbc8d.png)
But now I have a problem, I need to play the animation (duration: 20 ms) with the click of a button.
I did something like this
![image](https://user-images.githubusercontent.com/22659468/65732124-11077980-e0d1-11e9-8969-93b8a8802adc.png)
I create a state on which I check play animation or not
![image](https://user-images.githubusercontent.com/22659468/65732174-40b68180-e0d1-11e9-91ef-b809f2f6cfdf.png)
The animation is only played correctly for the first time. So I don't think my approach is correct. Could you help me with it?

**Comment by umberto-sonnino** [comment]
Are you resetting `playLeft` so it can play again?

If you could share your code, we can take a look!

**Comment by bedryck** [comment]
`import 'package:flutter/material.dart';
import 'package:flare_flutter/flare_actor.dart';
import 'package:flare_flutter/flare_controls.dart';

class Test extends StatefulWidget {
  Test({Key key}) : super(key: key);
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return TestState();
  }
}

class TestState extends State<Test> {
  String position = 'center';

  final FlareControls controls = FlareControls();

  void centerLeft() {
    controls.play("centerLeft");
  }

  void leftCenter() {
    controls.play("leftCenter");
  }

  void centerRight() {
    controls.play("centerRight");
  }

  void rightCenter() {
    controls.play("rightCenter");
  }

  void changePosition(direction) {
    if (direction > 0) {
      switch (position) {
        case "center":
          centerRight();
          setState(() {
            position = 'right';
          });

          break;
        case "left":
          leftCenter();
          setState(() {
            position = 'center';
          });

          break;
        default:
          break;
      }
    } else {
      switch (position) {
        case "center":
          centerLeft();
          setState(() {
            position = 'left';
          });

          break;
        case "right":
          rightCenter();
          setState(() {
            position = 'center';
          });

          break;
        default:
          break;
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // controls.play('earsRotate');
    double initial;
    double distance;
    // TODO: implement build
    return Scaffold(
        body: Material(
            child: Column(
      children: <Widget>[
        Expanded(
            child: Container(
                color: Colors.white,
                child: GestureDetector(
                    child: Stack(
                      children: <Widget>[
                        FlareActor("animation/space.flr",
                            alignment: Alignment.center,
                            fit: BoxFit.fitWidth,
                            animation: 'sunRotate'),
                        FlareActor("animation/earth.flr",
                            alignment: Alignment.center,
                            fit: BoxFit.fitWidth,
                            animation: 'earthRotate',
                            controller: controls),
                      ],
                    ),
                    onPanStart: (DragStartDetails details) {
                      initial = details.globalPosition.dx;
                    },
                    onPanUpdate: (DragUpdateDetails details) {
                      distance = details.globalPosition.dx - initial;
                    },
                    onPanEnd: (DragEndDetails details) {
                      initial = 0.0;
                      changePosition(distance);
                      //+ve distance signifies a drag from left to right(start to end)
                      //-ve distance signifies a drag from right to left(end to start)
                    })))
      ],
    )));
  }

  @override
  ValueNotifier<bool> isActive;
}
`

**Comment by bedryck** [comment]
```import 'package:flutter/material.dart';
import 'package:flare_flutter/flare_actor.dart';
import 'package:flare_flutter/flare_controls.dart';

class Test extends StatefulWidget {
  Test({Key key}) : super(key: key);
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return TestState();
  }
}

class TestState extends State<Test> {
  String position = 'center';

  final FlareControls controls = FlareControls();

  void centerLeft() {
    controls.play("centerLeft");
  }

  void leftCenter() {
    controls.play("leftCenter");
  }

  void centerRight() {
    controls.play("centerRight");
  }

  void rightCenter() {
    controls.play("rightCenter");
  }

  void changePosition(direction) {
    if (direction > 0) {
      switch (position) {
        case "center":
          centerRight();
          setState(() {
            position = 'right';
          });

          break;
        case "left":
          leftCenter();
          setState(() {
            position = 'center';
          });

          break;
        default:
          break;
      }
    } else {
      switch (position) {
        case "center":
          centerLeft();
          setState(() {
            position = 'left';
          });

          break;
        case "right":
          rightCenter();
          setState(() {
            position = 'center';
          });

          break;
        default:
          break;
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // controls.play('earsRotate');
    double initial;
    double distance;
    // TODO: implement build
    return Scaffold(
        body: Material(
            child: Column(
      children: <Widget>[
        Expanded(
            child: Container(
                color: Colors.white,
                child: GestureDetector(
                    child: Stack(
                      children: <Widget>[
                        FlareActor("animation/space.flr",
                            alignment: Alignment.center,
                            fit: BoxFit.fitWidth,
                            animation: 'sunRotate'),
                        FlareActor("animation/earth.flr",
                            alignment: Alignment.center,
                            fit: BoxFit.fitWidth,
                            animation: 'earthRotate',
                            controller: controls),
                      ],
                    ),
                    onPanStart: (DragStartDetails details) {
                      initial = details.globalPosition.dx;
                    },
                    onPanUpdate: (DragUpdateDetails details) {
                      distance = details.globalPosition.dx - initial;
                    },
                    onPanEnd: (DragEndDetails details) {
                      initial = 0.0;
                      changePosition(distance);
                      //+ve distance signifies a drag from left to right(start to end)
                      //-ve distance signifies a drag from right to left(end to start)
                    })))
      ],
    )));
  }

  @override
  ValueNotifier<bool> isActive;
}
```

**Comment by bedryck** [comment]
this is strange, but I found the solution without creating a full controller. I create one background animation and another animation on top of it

**Comment by bedryck** [comment]
Also, I'm new in a flutter, maybe there's a better way to play animation on button tap using a controller?

**Comment by bedryck** [comment]
```import 'package:flare_dart/math/mat2d.dart';
import 'package:flutter/material.dart';
import 'package:flare_flutter/flare_actor.dart';
import 'package:flare_flutter/flare_controls.dart';

import 'package:flare_flutter/flare_controller.dart';

import 'package:flare_flutter/flare.dart';

class Test extends StatefulWidget {
  Test({Key key}) : super(key: key);
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return TestState();
  }
}

class TestState extends State<Test> with FlareController {
  bool isAllowCenterLeft = false;
  bool isAllowleftCenter = false;

  FlutterActorArtboard _artboard;
  FlareAnimationLayer _centerLeftAnimation;
  FlareAnimationLayer _leftCenterAnimation;



  @override
  bool advance(FlutterActorArtboard artboard, double elapsed) {
    if (isAllowCenterLeft) {
      print('center_left');
      _centerLeftAnimation.time += elapsed;
      _centerLeftAnimation.apply(artboard);
      if (_centerLeftAnimation.isDone) {
        setState(() {
          isAllowCenterLeft = false;
        });
      }
    }

    if (isAllowleftCenter) {
      print('left_center');

      _leftCenterAnimation.time += elapsed;
      _leftCenterAnimation.apply(artboard);
      if (_leftCenterAnimation.isDone) {
        setState(() {
          isAllowCenterLeft = false;
        });
      }
    }

    return true;
  }

    @override
  void initialize(FlutterActorArtboard artboard) {
    _artboard = artboard;

    _centerLeftAnimation = FlareAnimationLayer()
      ..animation = _artboard.getAnimation("centerLeft")
      ..mix = 1.0;

    _leftCenterAnimation = FlareAnimationLayer()
      ..animation = _artboard.getAnimation("leftCenter")
      ..mix = 1.0;
  }


  onCenterLeft() {
    setState(() {
      isAllowCenterLeft = true;
    });
  }

  onLeftCenter() {
    setState(() {
      isAllowleftCenter = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
        body: Material(
            child: Column(
      children: <Widget>[
        Expanded(
          child: FlareActor("animation/earth.flr",
              alignment: Alignment.center,
              fit: BoxFit.fitWidth,
              animation: 'earthRotate',
              controller: this),
        ),
        FlatButton(
          child: Text('centerLeft'),
          onPressed: onCenterLeft,
        ),
        FlatButton(
          child: Text('leftCenter'),
          onPressed: onLeftCenter,
        )
      ],
    )));
  }

  @override
  void setViewTransform(Mat2D viewTransform) {
    // TODO: implement setViewTransform
  }
}
```
so, I did return the code to the previous version. but the problem remains the same, this is only playing the first time.

**Comment by bedryck** [comment]
https://drive.google.com/file/d/1Srmky42yEHocJK2dGU1Pbs0v8jjxs_91/view?usp=sharing

**Comment by umberto-sonnino** [comment]
It looks like both animations aren't getting their time reset to their starting point, so they're not allowed to play again. They're keeping on playing from the point you left the at in the `advance()` function.

If you want to simplify the logic a little bit you can try this with `FlareControls`:
```
class TestState extends State<Test> {
  EarthController _earthController;

  @override
  void initState() {
    _earthController = EarthController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Material(
            child: Column(
      children: <Widget>[
        Expanded(
          child: FlareActor("assets/earth.flr",
              alignment: Alignment.center,
              fit: BoxFit.fitWidth,
              animation: 'earthRotate',
              controller: _earthController),
        ),
        FlatButton(
          child: Text('centerLeft'),
          onPressed: () => _earthController.onMove(MoveDirection.CenterLeft),
        ),
        FlatButton(
          child: Text('leftCenter'),
          onPressed: () => _earthController.onMove(MoveDirection.LeftCenter),
        )
      ],
    )));
  }
}


enum MoveDirection {
  CenterLeft,
  LeftCenter
}

class EarthController extends FlareControls {
  onMove(MoveDirection moveDirection) {
    switch(moveDirection) {
      case MoveDirection.CenterLeft:
        super.play("centerLeft");
        break;
      case MoveDirection.LeftCenter:
        super.play("leftCenter");
        break;
      default:
        break;
    }
  }
}
```

**Comment by bedryck** [comment]
Looks great, thank you very much. You have a great service, but as for me, I lack documentation for the flare controller. I found some examples but that was not enough. Good luck!
