### ISSUE TITLE
[1.6.2] Animation partially not loaded

### ISSUE THREAD

**Issue by TheFe91** [2d-inc/Flare-Flutter#179]
I've forked and edited a nice animation
https://www.2dimensions.com/a/TheFe91/files/flare/rosso-loader

Unfortunately when I call this animation in my app it shows like this:
https://i.stack.imgur.com/OYnba.jpg

I use it in this way:
`FlareActor(
                  'assets/RossoLoader.flr',
                  fit: BoxFit.fitWidth,
                  alignment: Alignment.center,
                  animation: 'Loading',
                ),`

Any idea?
Thanks!

**Comment by umberto-sonnino** [comment]
We're currently working on a fix, thanks for the report!

**Comment by luigi-rosso** [comment]
Please give this a try in the latest ```flare_flutter: ^1.7.0``` and let us know if it fixes the issue for you!

**Comment by TheFe91** [comment]
Unfortunately I'm no more able to build. This is the error the compilers give me (iOS and Android):

Compiler message:
/Library/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.7.0/lib/flare.dart:1109:11: Error: No named parameter with the name 'cacheWidth'.
          cacheWidth: cacheWidth, cacheHeight: cacheHeight);
          ^^^^^^^^^^
/Library/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.7.0/lib/flare.dart:1106:33: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
    var load = networkImage.load(val, (Uint8List bytes,

**Comment by luigi-rosso** [comment]
Which Flutter channel are you using?

**Comment by TheFe91** [comment]
the stable one

**Comment by sotoyjuan** [comment]
I'm getting the same exact error as @TheFe91 . Running latest stable version too.

**Comment by luigi-rosso** [comment]
Looks like there's a breaking change between stable and dev/master. The dev and master channels have a slightly different signature for the instantiateImageCodec call. Please try ```flare_flutter: ^1.7.1``` 

Apologies for the hassle!

**Comment by TheFe91** [comment]
Wonderful! Now It's working perfectly! Thanks for all the work!
If it's OK for you, I'll close the issue

**Comment by luigi-rosso** [comment]
Great, no problem, and thank you for reporting and testing!
