### ISSUE TITLE
Loop animation, wait until it finish a lap to start another one #62

### ISSUE THREAD

**Issue by pazhut** [2d-inc/Flare-Flutter#182]
i had tried using FlareProgressIndicator from the above . support case, i got a compile error that iSActive (setter and getter) is missing, i tried adding the following lines:

@override
  ValueNotifier<bool> isActive;

but animation do not run

any suggestion on how to solve this?

Thanks

**Comment by luigi-rosso** [comment]
Hi @pazhut can you share your source? The isActive property is defined on a FlareController and helps FlareActor know whether or not to continue advancing (updating and drawing) the Flare animation.

**Comment by pazhut** [comment]
Hi Luigi

i had found an hint on your release notes page that mentioned changing into
mixin, i replace the implement statement to with and this seems to be
working now

attached is the latest version for your reference

Thanks for your support

paz
