### ISSUE TITLE
'ActorNode' is not of subtype 'FlutterPath'

### ISSUE THREAD

**Issue by innotechBymoen** [2d-inc/Flare-Flutter#185]
I am running into issues with only one of my flare exports. The rest of them work fine, but this one keeps throwing a stack trace. I can also simply replace this animation in my code (i.e. the asset file) and the different animation works just fine, so it isn't the specific code.

```
Unhandled Exception: type 'ActorNode' is not a subtype of type 'FlutterPath' in type cast
E/flutter ( 5758): #0      FlutterActorShape.initializeGraphics (package:flare_flutter/flare.dart:179:40)
E/flutter ( 5758): #1      ActorArtboard.initializeGraphics (package:flare_dart/actor_artboard.dart:573:16)
E/flutter ( 5758): #2      FlareActorRenderObject._instanceArtboard (package:flare_flutter/flare_actor.dart:273:14)
E/flutter ( 5758): #3      FlareActorRenderObject.load (package:flare_flutter/flare_actor.dart:304:5)
E/flutter ( 5758): <asynchronous suspension>
E/flutter ( 5758): #4      FlareActorRenderObject.filename= (package:flare_flutter/flare_actor.dart:263:5)
E/flutter ( 5758): #5      FlareActor.createRenderObject (package:flare_flutter/flare_actor.dart:81:9)
```

Has anyone ran into this with newer .flr files? All of the old ones I have made work just fine with my normal workflow.

**Comment by luigi-rosso** [comment]
Hi @innotechBymoen, sorry to hear that, it does seem like something is wrong with that file. Could you share the .flr file and a link to the file on 2dimensions.com?

**Comment by innotechBymoen** [comment]
Thanks for looking into this @luigi-rosso 
[login_state.zip](https://github.com/2d-inc/Flare-Flutter/files/3817481/login_state.zip)
https://www.2dimensions.com/a/nikodragicevic/files/flare/lg-status

**Comment by luigi-rosso** [comment]
It seems to be for me. Which version of ```flare_flutter``` do you have defined in your pubspec.yaml? Try upgrading to the latest, ```flare_flutter: ^1.6.5``` and see if that makes a difference!

**Comment by innotechBymoen** [comment]
Ah of course. That has worked, Thanks!

**Comment by luigi-rosso** [comment]
Great, glad it was so easy!
