### ISSUE TITLE
PNG assets not showing in Flutter

### ISSUE THREAD

**Issue by majindageta** [2d-inc/Flare-Flutter#186]
Hi,
by importing a flare file into a flutter project we're not able to see any of the PNG image that are included in the flare project.  The vector drawing objects are visible.
No error is logged.
Thank you

**Comment by luigi-rosso** [comment]
Hi @majindageta. I just did a test and it seems to be working here. Can you share the exported .flr file and a link to the file on 2dimensions.com? Are you exporting binary or json?

**Comment by majindageta** [comment]
Hi, thank you for the answer. I was trying using the example downloaded
from git hub and  not by downloading the latest version.

Using the latest one works fine.

Sorry, I thought using the example from git hub had the latest version...
My bad.

Sorry and thanks again

Il gio 7 nov 2019, 19:10 Luigi Rosso <notifications@github.com> ha scritto:

**Comment by luigi-rosso** [comment]
No problem, glad it was an easy fix!
