### ISSUE TITLE
Design tool

### ISSUE THREAD

**Issue by ghost** [2d-inc/Flare-Flutter#2]
Is the design tool downloadable so I can run it on desktop ?

Create project btw ! Really huge gamechanger.

**Comment by Kabir121** [comment]
What is the use of main.old.dart ??

And it is also showing me error on draw

**Comment by luigi-rosso** [comment]
Hi @Kabir121, I’ll take a look at this soon and get back to you later today. Thanks for trying this out!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kabir121** [comment]
Hi Luigi

I have one more question, I can only able to see Filip.flr on mobile and other falre files which are available in assets folder are not working. And sometimes Filip file is not not visible to me on screen.

Screenshot attached ;)
![2picturemessage_gjh5vmfa snq](https://user-images.githubusercontent.com/1772926/49565461-34e4ad80-f94d-11e8-88f3-3d602e4350de.png)

**Comment by luigi-rosso** [comment]
Does that happen when hot reloading, fresh start, or both? Could you share the project or is this just the example?

**Comment by Kabir121** [comment]
It is the sample example which I downloaded from github

**Comment by gedw99** [comment]
@luigi-rosso Can i get an answer to the original question :) ? KInd of got hijacked by @Kabir121 :)

**Comment by luigi-rosso** [comment]
Sorry forgot to answer :) No, it currently cannot be downloaded. However, we have plans for making it easier to work offline. Currently your work will continue saving if you have a hiccup in your connection, and it will sync up when the connection is working again.

**Comment by neurowave** [comment]
We are tracking the improved offline experience here: https://github.com/2d-inc/support/issues/151

Should we close this issue and track @Kabir121's issue separately? Or is that closed as well? @luigi-rosso
