### ISSUE TITLE
Blur, Shadows not working

### ISSUE THREAD

**Issue by nikitattt** [2d-inc/Flare-Flutter#203]
Tried recently added Blur, Inner, Drop Shadows and found that they are not rendered in Flutter. 
Plugin version: `1.8.1`, stable channel.

**Comment by luigi-rosso** [comment]
Hi @nikitattt, can you send a link to your file on https://rive.app?

**Comment by nikitattt** [comment]
Hi @luigi-rosso, here you go: https://rive.app/a/nikita.nvgames/files/flare/nixie-lamp

**Comment by luigi-rosso** [comment]
Thanks @nikitattt, could you post a screenshot of what you see in Flutter? I do see the effects, but some of them look wrong. I need to do a little more investigation but I'm still traveling for the next two days so it may take a little more time to get to the bottom of this. Here's what I see in Flutter, do you see the same thing?

![image](https://user-images.githubusercontent.com/454182/70856546-cb14c180-1f19-11ea-9ff4-83a4a3d6d7ae.png)

One thing I did want to mention is that it looks like you're using a lot of effects on individual shapes, you can apply the effects to nodes too by grouping shapes together. This will be more performant at runtime.

**Comment by Effizjens** [comment]
Hey,
I guess this is kind of the same problem. By adding an inner shadow there is also an  blur effect.
This is my rive file https://rive.app/a/Effizjens/files/flare/new-file .

This is what I see in Flutter.
![Screenshot_20191216-175851](https://user-images.githubusercontent.com/11580136/70926823-0f918180-202e-11ea-9122-107a0c330d34.png)

And here is my code using flare_flutter: ^1.8.2 and flutter v1.12.13+hotfix.5.

```
import 'package:flutter/material.dart';
import 'package:flare_flutter/flare_actor.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        backgroundColor: Colors.amberAccent,
        body: FlareActor(
          "assets/File.flr",
          alignment: Alignment.center,
          fit: BoxFit.contain,
        ),
      ),
    );
  }
}

```

**Comment by nikitattt** [comment]
@luigi-rosso yes, I see absolutely the same thing as in your example. 

P.S. Thanks. I'll try to achieve the same effects with nodes. One more point I wanted to mention(not really related to this issue), when working with files that have many elements(example: https://rive.app/a/nikita.nvgames/files/flare/nixie) I notice a significant slowdown in client interface. I don't know if this is an issue and is it related to rive client rendering speeds. Maybe you have advice on how to organize many elements for fast work?

**Comment by Chaitanyabsprip** [comment]
I have the same issue
what is the fix?

**Comment by nikitattt** [comment]
Hi @luigi-rosso! How this issue is going? 
Planned to use elements with shadows and blur in Flutter Clock Challenge which deadline is on 20 January...

**Comment by avinath1998** [comment]
Yep same, still facing this shadow issue.

**Comment by kingcla** [comment]
Hi @luigi-rosso I am also facing the same problem (for the flutter clock challenge as well BTW). There is a shadow in my model and it appears blurred in Flutter.
 In Rive:
![image](https://user-images.githubusercontent.com/29022704/72463546-c4f15980-37d3-11ea-9819-9a9e641c3e8a.png)
In Flutter:
![image](https://user-images.githubusercontent.com/29022704/72463560-ca4ea400-37d3-11ea-98cc-f51d9fa2d0b1.png)

Can you please help us?

**Comment by luigi-rosso** [comment]
Apologies for the delay on this. Could everyone who is facing the issue please make sure to update your posts to include a link to your file (or please email the .flr2d files to luigi@rive.app)? Hoping to get this fixed in the next couple of days.

**Comment by Chaitanyabsprip** [comment]
https://rive.app/a/chaitanyabsprip/files/flare/neu-circle

**Comment by luigi-rosso** [comment]
Thanks! Please try version ```flare_flutter: ^2.0.1```, where it should be fixed.

**Comment by kingcla** [comment]
@luigi-rosso I just tried, it works!! Thanks ;)
