### ISSUE TITLE
Help Needed : I am Not able to Figure out how i can able to use Teddy | TrackingTextInput _controller and My controller both in TextField.

### ISSUE THREAD

**Issue by TheSunilVarma** [2d-inc/Flare-Flutter#207]
I have Extracted My TextWidget using like this To achieve my Custom UI TextField but not able to figure out where i can use Teddy _controller !? (because i am using my controller for input and password... to get and use it.)

Code...
**In My Login Page..**
`TrackingTextInput(customTextWid: CustomTextWid(focusNode: _focusNode, controller: _controller, workSansSemiBold: workSansSemiBold, envelope: _envelope, emailAddress: emailAddress)),
`
**In trackingtext_input.dart**
`  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
          top: 20.0, bottom: 20.0, left: 25.0, right: 25.0),
      child: widget.trackBuildWid); `

added customTextWid Parameter and succefully able to use and Show UI in app by returning my custom widget in Parameter in build of trackingtext_input.dart,
but how and where i need to use Teddy _controller to animate Teddy !

**I am Trying to implement in this Login UI** 
https://github.com/huextrat/TheGorgeousLogin

Any clue or help will be highly Appreciated !

Thanks in Advance !

**Comment by TheSunilVarma** [comment]
ScreenShot : 

![ss](https://user-images.githubusercontent.com/34575152/70938955-4470f900-206d-11ea-8575-c4a0656cfbf0.gif)

**Comment by she-who-codes** [comment]
[In this tutorial](https://medium.com/rive/building-an-interactive-login-screen-with-flare-flutter-749db628bb51), it breaks down each step so you can better understand the `teddy_controller` and `tracking_text_input` and how it relates to the input fields.

**Comment by TheSunilVarma** [comment]
Thanks For help...  i have read the Code and found the use case of teddy_controller and _controller,Now its working :)
