### ISSUE TITLE
Animation does not work after compiling in ios

### ISSUE THREAD

**Issue by hsnbsst** [2d-inc/Flare-Flutter#231]
It works in ios animation emulator and my own phone but it doesn't work when you compile and send it to test flight

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.6-pre.25, on Mac OS X 10.15.2 19C57, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by Karlculations** [comment]
I am having the same issue on Android as well. Works fine while debugging and testing, but doesn't show up in release mode.

**Comment by hsnbsst** [comment]
Fixed with flutter update

**Comment by Karlculations** [comment]
Yeah lol, you beat me to it. I updated just after sending that and realized it started working again.
