### ISSUE TITLE
The argument type 'Null Function(dynamic, dynamic)' can't be assigned to the parameter type 'ImageStreamListener'.

### ISSUE THREAD

**Issue by emadsoliman25** [2d-inc/Flare-Flutter#232]
Compiler message:
    ../../.pub-cache/hosted/pub.dartlang.org/flutter_plugin_pdf_viewer-1.0.3/lib/src/page.dart:33:26: Error: The argument type 'Null Function(dynamic, dynamic)' can't be assigned to the parameter type 'ImageStreamListener'.

**Comment by aurony** [comment]
Hi, have you solved this?

**Comment by emadsoliman25** [comment]
I changed the package to flutter_full_pdf_viewer and worked well
