### ISSUE TITLE
Color is not reacting to Theme changes

### ISSUE THREAD

**Issue by Ahmadre** [2d-inc/Flare-Flutter#256]
## Steps to reproduce

1. Create (or get) a random Flare file with rive.app
2. Export it as a binary file (.flr)
3. Import it in Flutter by this snippet (by the way `TinyColor` is working with other Icons. So `TinyColor` isn't the problem here):

```dart
import 'package:flare_flutter/flare_actor.dart';
import 'package:flutter/material.dart';
import 'package:tinycolor/tinycolor.dart';

IconButton(
  icon: FlareActor(
    'assets/flare/AnimatedMenuButton.flr',
     color: TinyColor(Theme.of(context).scaffoldBackgroundColor).isLight() ? Colors.black : Colors.white,
     animation: 'idle',
     fit: BoxFit.contain,
  ),
  onPressed: toggleMenu,
),
```

__Sidenote__: I also tried:
```dart
color: Theme.of(context).brightness == Brightness.light ? Colors.black : Colors.white,
```

but none of them are working. It seeems, that `FlareActor` is ignoring `Theme` maybe?

4. Have the `theme` and `darkTheme` setup in `MaterialApp`. Now `ThemeMode` will be: `ThemeMode.system`, which will automatically switch `Brightness` of the app.
5. Go to settings (android or ios) and change your theme. It doesn't matter if you switch from dark -> light or from light -> dark.
6. Now go back into the flutter app. Bam.

### Expected results

FlareActor will detect `ThemeMode` switch and rerender the Color.

### Actual results
Here's an example of my custom Menu-Button on the top left of my AppBar:

![flare_error](https://user-images.githubusercontent.com/18512224/83158801-88c8f080-a105-11ea-89f3-0963fb2d5585.gif)

### Logs

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.145, on Mac OS X 10.15.5 19F96, locale
    de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)
```

Thanks 😊

**Comment by Ahmadre** [comment]
I did a workaround by exporting different flare assets with different colors. But then the color property is maybe useless.

**Comment by umberto-sonnino** [comment]
Is your 'idle' animation looping? If possible, could you share your Rive file url?

**Comment by Ahmadre** [comment]
@umberto-sonnino I would like to send you the file on an email address or something, but not on public. Would you write via my github account email?

**Comment by Ahmadre** [comment]
Thanks! It works now :)

**Comment by alnitak** [comment]
So, how did you solved this? :)
