### ISSUE TITLE
How to reset model?

### ISSUE THREAD

**Issue by mrxten** [2d-inc/Flare-Flutter#259]
Hi, before start another animation I need to fully reset model, is it possible?

**Comment by umberto-sonnino** [comment]
Are you trying to reset your Flare file to what it looks like in the 'Design' pose in the Flare editor?

Our runtimes will allow you to work with the animations in the editor, so if you want to have everything go back to 'Design' mode, you could create a placeholder animation in which you key everything at the start, and swap back to that when needed.

**Comment by mrxten** [comment]
I found another way. For reset animation I just reset flare widget. For that need wrap actor with some widget with unique key, and when need reset model change unique key

```dart
Container(
  key: _key,
  child: FlareActor(
    'modelAssetUri'
    controller: _controller,
  ),
);
```

```dart
setState(() {
  _key = UniqueKey();
});
```
