### ISSUE TITLE
Flutter not respecting Even-Odd fill rule for intersecting paths

### ISSUE THREAD

**Issue by positev** [2d-inc/Flare-Flutter#27]
<img width="1920" alt="screen shot 2019-01-04 at 11 03 15 pm" src="https://user-images.githubusercontent.com/44409350/50726750-0803f180-10d7-11e9-99ae-ee19c2c5d88e.png">
<img width="1920" alt="screen shot 2019-01-04 at 11 03 44 pm" src="https://user-images.githubusercontent.com/44409350/50726751-0803f180-10d7-11e9-8e00-b8138598bdd3.png">

Intersecting paths in a shape with the even odd fill rule are treated as if the fill rule is set to nonzero in flutter.

**Comment by luigi-rosso** [comment]
Thanks for reporting this! Give version 1.0.9 a try, it should be fixed now.

**Comment by positev** [comment]
I updated to 1.0.9 but saw no change in flutter

**Comment by positev** [comment]
interestingly i downloaded a new copy of the flare file and placed it in the animations folder and it suddenly worked.. Thanks!
