### ISSUE TITLE
can not use `.flr2d` file

### ISSUE THREAD

**Issue by HannibalKcc** [2d-inc/Flare-Flutter#270]
> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: FormatException: Unexpected character (at character 1)
E/flutter (17128): PK

[bluetooth_connect_animation.zip](https://github.com/2d-inc/Flare-Flutter/files/5040885/bluetooth_connect_animation.zip)

i am new for Flare-Flutter ，tks for any help.

**Comment by umberto-sonnino** [comment]
There are two options for exporting files, you can read about them [here](https://docs.rive.app/rive/exporting-assets). 
.flr2d files are backup files, if you use the other option in the menu you'll be able to run it with this package.

**Comment by HannibalKcc** [comment]
@umberto-sonnino thank you so much.

my designer just give me a .flr2d file, so i did not realize it.
