### ISSUE TITLE
Docs/Guide/Tutorial?

### ISSUE THREAD

**Issue by normancarcamo** [2d-inc/Flare-Flutter#280]
I'm trying hard to implement all the classes as a puzzle to know how the classes work, is there any guide to follow? I would like to pause and blend animations manually from flutter using the controller but I don't have much luck.

**Comment by umberto-sonnino** [comment]
You can start by taking a look at the [example folder](/2d-inc/Flare-Flutter/tree/stable/example) in the repo. There are a few sample apps that might be a good starting point!

Also, you can find a few articles on [Medium](https://medium.com/rive/) - [here's one](https://medium.com/rive/building-an-interactive-login-screen-with-flare-flutter-749db628bb51) that explains some of the controllers' concepts & APIs.

**Comment by normancarcamo** [comment]
Thank you.
