### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by adarsh-technocrat** [2d-inc/Flare-Flutter#291]
### **Description**

- Migrate to sound null safety
- Bump up package version

**Comment by nilsreichardt** [comment]
Here are some helpful resources:
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by NarHakobyan** [comment]
Is this library depreciated?

**Comment by talamaska** [comment]
Yes, please migrate i have animations that are still impossible to make on rive2 like jelly bones and other bunch of things which are impossible to make in rive 2 for now

**Comment by marcos930807** [comment]
Is there a roadmap, timeline, etc, for when will this be available?? i have a dependency on this package.

**Comment by ir4ever** [comment]
waiting for it

**Comment by NarHakobyan** [comment]
@luigi-rosso do you have plans to migrate to null-safety?

**Comment by alanlanglois** [comment]
> Is this library depreciated?

Sounds like: https://github.com/rive-app/rive-flutter

**Comment by mjohnsullivan** [comment]
We're going to focus on null safety migration for this package next week to get a release out shortly.
