### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by itsJoKr** [2d-inc/Flare-Flutter#292]
Currently, it is very hard to debug when something fails. Even simple stuff, like entering the wrong animation-name, it should not fail silently but give the developer some info.

Like some other packages, I suggest either singleton or field where the developer can set debug mode:
```
Flare.setDebug(true);
```

And with this set, the console will be filled with useful data like:
```
Starting animation "idle".
Stopping animation "idle".
Could not find animation "ilde".
Animation "x" could not be run because...
```

Does the flare have something like this?

**Comment by luigi-rosso** [comment]
That's an interesting idea! We don't currently have something like this planned. We're working on the next iteration of Flare over at https://github.com/rive-app/rive. I'd encourage you to try that out and perhaps make this request there!
