### ISSUE TITLE
Migration to Null-Safety

### ISSUE THREAD

**Issue by deimantasa** [2d-inc/Flare-Flutter#294]
Hello team,

Is there any ETA for migration to be done?

Cheers

**Comment by deimantasa** [comment]
Seems that something is in works https://github.com/2d-inc/Flare-Flutter/pull/293

**Comment by mjohnsullivan** [comment]
Our plan is to work on this in earnest next week to get a release out shortly.

**Comment by mjohnsullivan** [comment]
Duplicate of #291
