### ISSUE TITLE
LateInitializationError

### ISSUE THREAD

**Issue by FredslundMagnus** [2d-inc/Flare-Flutter#297]
I got following error using:
flare_flutter: ^3.0.0-nullsafety.0

════════ Exception caught by rendering library ═════════════════════════════════
The following LateError was thrown during paint():
LateInitializationError: Field '_setupAABB@322245341' has not been initialized.

The relevant error-causing widget was
FlareActor
lib\card.dart:126
When the exception was thrown, this was the stack
0      FlareActorRenderObject._setupAABB (package:flare_flutter/flare_actor.dart)
package:flare_flutter/flare_actor.dart:1
1      FlareActorRenderObject.aabb
package:flare_flutter/flare_actor.dart:221
2      FlareRenderBox.paint
package:flare_flutter/flare_render_box.dart:175
3      RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2322
4      PaintingContext.paintChild
package:flutter/…/rendering/object.dart:189
...
The following RenderObject was being processed when the exception was fired: FlareActorRenderObject#eb411
RenderObject: FlareActorRenderObject#eb411
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=179.7, h=136.7)
    size: Size(179.7, 136.7)
════════════════════════════════════════════════════════════════════════════════

It only happened for one of my .flr files, however, on previous versions of flare_flutter there was no error. I can probably fix this by redrawing that .flr file, however, this problem might stil be worth fixing.

**Comment by luigi-rosso** [comment]
Hey @FredslundMagnus thanks for reporing this. Could you post the file here or send it to luigi@rive.app if it's a private file?

**Comment by FredslundMagnus** [comment]
Hey @luigi-rosso  I have sent the file to your mail, if a link is good enough then:
https://flare.rive.app/a/MagnusF/files/flare/timecol

**Comment by uttufy** [comment]
I am having the same issue

**Comment by luigi-rosso** [comment]
Please give ```flare_flutter: 3.0.0-nullsafety.1``` a shot, the issue should be resolved!

**Comment by uttufy** [comment]
> Please give `flare_flutter: 3.0.0-nullsafety.1` a shot, the issue should be resolved!

This resolved my issue. Thank you 👍

**Comment by luigi-rosso** [comment]
Glad to hear it! Thanks for reporting.

**Comment by azhansy** [comment]
version:3.0.0-nullsafety.1、3.0.1，there is this problem：
---------------------------------------------
[ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: Exception: LateInitializationError: Field '_paint@2346459774' has not been initialized., stack trace: #0      FlutterActorImage._paint (package:flare_flutter/flare.dart)
E/flutter (27275): #1      FlutterActorImage.onBlendModeChanged (package:flare_flutter/flare.dart:503:5)
E/flutter (27275): #2      FlutterActorDrawable.blendMode= (package:flare_flutter/flare.dart:226:5)
E/flutter (27275): #3      FlutterActorDrawable.blendModeId= (package:flare_flutter/flare.dart:233:5)
E/flutter (27275): #4      ActorDrawable.read (package:flare_flutter/base/actor_drawable.dart:77:17)
E/flutter (27275): #5      ActorImage.read (package:flare_flutter/base/actor_image.dart:305:19)
E/flutter (27275): #6      ActorArtboard.readComponentsBlock (package:flare_flutter/base/actor_artboard.dart:387:34)
E/flutter (27275): #7      ActorArtboard.read (package:flare_flutter/base/actor_artboard.dart:349:11)
E/flutter (27275): #8      Actor.readArtboardsBlock (package:flare_flutter/base/actor.dart:180:22)
E/flutter (27275): #9      Actor.load (package:flare_flutter/base/actor.dart:85:11)
E/flutter (27275): #10     FlutterActor.loadFromByteData (package:flare_flutter/flare.dart:165:17)
E/flutter (27275): #11     _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:83:34)
E/flutter (27275): #12     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:65)
E/flutter (27275): #13     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:89:5)
E/flutter (27275): #14     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (27275): #15     _spawn (package:flutter/src/foundation/_isolates_io.dart:87:35)
E/flutter (27275): #16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
E/flutter (27275): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (27275): 
E/flutter (27275): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: Exception: LateInitializationError: Field '_paint@2346459774' has not been initialized., stack trace: #0      FlutterActorImage._paint (package:flare_flutter/flare.dart)
E/flutter (27275): #1      FlutterActorImage.onBlendModeChanged (package:flare_flutter/flare.dart:503:5)
E/flutter (27275): #2      FlutterActorDrawable.blendMode= (package:flare_flutter/flare.dart:226:5)
E/flutter (27275): #3      FlutterActorDrawable.blendModeId= (package:flare_flutter/flare.dart:233:5)
E/flutter (27275): #4      ActorDrawable.read (package:flare_flutter/base/actor_drawable.dart:77:17)
E/flutter (27275): #5      ActorImage.read (package:flare_flutter/base/actor_image.dart:305:19)
E/flutter (27275): #6      ActorArtboard.readComponentsBlock (package:flare_flutter/base/actor_artboard.dart:387:34)
E/flutter (27275): #7      ActorArtboard.read (package:flare_flutter/base/actor_artboard.dart:349:11)
E/flutter (27275): #8      Actor.readArtboardsBlock (package:flare_flutter/base/actor.dart:180:22)
E/flutter (27275): #9      Actor.load (package:flare_flutter/base/actor.dart:85:11)
E/flutter (27275): #10     FlutterActor.loadFromByteData (package:flare_flutter/flare.dart:165:17)
E/flutter (27275): #11     _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:83:34)
E/flutter (27275): #12     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:65)
E/flutter (27275): #13     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:89:5)
E/flutter (27275): #14     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (27275): #15     _spawn (package:flutter/src/foundation/_isolates_io.dart:87:35)
E/flutter (27275): #16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
E/flutter (27275): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (27275):

**Comment by azhansy** [comment]
My flare file size more than 10MB，maybe this is the cause of the problem?

**Comment by tnaseem** [comment]
I'm having the same issue as @azhansy. I've just updated my app from Flutter 1.x.x to 2.x.x and using flare_flutter 3.0.2.

Everything was working fine under Flutter 1.x.x, but since upgrading my code to work with 2.2.3, this is the only issue I'm experiencing. The error output is:

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Exception: LateInitializationError: Field '_paint@235459774' has not been initialized.
#0      FlutterActorImage._paint (package:flare_flutter/flare.dart)
#1      FlutterActorImage.onBlendModeChanged (package:flare_flutter/flare.dart:505:5)
#2      FlutterActorDrawable.blendMode= (package:flare_flutter/flare.dart:226:5)
#3      FlutterActorDrawable.blendModeId= (package:flare_flutter/flare.dart:234:5)
#4      ActorDrawable.read (package:flare_flutter/base/actor_drawable.dart:77:17)
#5      ActorImage.read (package:flare_flutter/base/actor_image.dart:305:19)
#6      ActorArtboard.readComponentsBlock (package:flare_flutter/base/actor_artboard.dart:387:34)
#7      ActorArtboard.read (package:flare_flutter/base/actor_artboard.dart:349:11)
#8      Actor.readArtboardsBlock (package:flare_flutter/base/actor.dart:180:22)
#9      Actor.load (package:flare_flutter/base/actor.dart:85:11)
#10     FlutterActor.loadFromByteData (package:flare_flutter/flare.dar<…>
```

I created a helper class for my Flare/Rive animations as below:

```
class Rive {

  // Singleton
  static final Rive _instance = new Rive.internal();
  factory Rive() => _instance;
  Rive.internal();

  final Map<String, AssetFlare> _assets = {};


  // Initialise the Flare assets.
  Future<void> init() async {
    animAsset.forEach((name, filename) {
      _assets[name] = AssetFlare(bundle: rootBundle, name: filename);
    });

    // Don't prune the Flare cache, keep cached files ready to be re-displayed.
    FlareCache.doesPrune = false;
    await _cacheAssets();
  }

  // Play the named Flare animation asset.
  Widget play({
    @required String name,
    @required String animation,
    String artboard,
    FlareController controller,
    bool isPaused = false,
    Alignment alignment = Alignment.center,
    BoxFit fit = BoxFit.contain,
    bool antialias = false,
    void Function(String) callback,
  }) {
    return FlareActor.asset(_assets[name],
      animation: animation,
      artboard: artboard,
      controller: controller,
      isPaused: isPaused,
      alignment: alignment,
      fit: fit,
      antialias: antialias,
      callback: callback,
    );
  }

  // Load all the Flare assets into the cache.
  Future<void> _cacheAssets() async =>
    _assets.forEach((name, asset) async => await cachedActor(asset));

  // Load the specified Flare asset into the cache.
  Future<void> cacheAsset(String name) async => await cachedActor(_assets[name]);
}
```

Basically, on initialisation, I cache the flare assets so they're all ready to be animated. Then call the `play()` function to rn it.

This all used to work beautifully in the past. Now, with Flutter 2.x I'm getting the above error (even if I don't cache the files and attempt to play the files directly). It appears to be that `_paint` is not getting initialised in `flare.dart`.

Any pointers are most appreciated!
