### ISSUE TITLE
Difference between flare-flutter and rive-flutter

### ISSUE THREAD

**Issue by ChristianKleineidam** [2d-inc/Flare-Flutter#303]
It looks to me like both packages are maintained and by the same authors. It would be great if the descriptions of them would provide guidance about which of the two to use.

**Comment by umberto-sonnino** [comment]
Hi @ChristianKleineidam! Both packages are developed by our team, that is correct, but they are used with two different products:
- Flare-Flutter for [Rive 1](https://flare.rive.app)
- rive-flutter for [Rive 2](https://rive.app)

We talked about a few more nuances in #296

**Comment by ChristianKleineidam** [comment]
In the other issue you say "The intention is very much to help the community migrate over to Rive as both the editor and new runtimes are what we're focusing our efforts on with regards to new features." If that's the case it would be helpful to communicate the intention of people to migrate to Rive on the flare-flutter package page.

**Comment by umberto-sonnino** [comment]
> In the other issue you say "The intention is very much to help the community migrate over to Rive as both the editor and new runtimes are what we're focusing our efforts on with regards to new features." If that's the case it would be helpful to communicate the intention of people to migrate to Rive on the flare-flutter package page.

We updated the README with those instructions..!

**Comment by ChristianKleineidam** [comment]
Great :)
