### ISSUE TITLE
Clear Memory after finish an animation

### ISSUE THREAD

**Issue by nizwar** [2d-inc/Flare-Flutter#310]
My application have lots of animation works, because of this the memory usage stack up,
is there any way to clear memories that already used by Flare, its happened like it still consume the memory even the animation finished or disposing the screen or widget... this going more wildly when i rejoin/restart the screen/widget, somehow the memory stack up more and more

![Screen Shot 2021-07-16 at 20 40 51](https://user-images.githubusercontent.com/33113137/125957182-7aa119a7-74b8-450d-a79d-bd32798e278a.png)

**Comment by luigi-rosso** [comment]
The memory usage is due to Skia's memory cache, it should free up some 15 seconds after the object is no longer drawn. This is built into Flutter.  There isn't much Flare can do to change this.

**Comment by nizwar** [comment]
In my case, the memory doesn't free up after 15 seconds, even i dispose the screen/widget that contain flare inside... if its not possible on flare side,  i'll open issues on flutter development then, thanks for you response
