### ISSUE TITLE
Can't load FlareActor.bundle on Android

### ISSUE THREAD

**Issue by nizwar** [2d-inc/Flare-Flutter#311]
I've store all my animation on getTemporaryDirectory (because its downloaded from server),
so i write something like this

```dart
 FlareActor.bundle(
     filename,
     bundle: rootBundle,  
     controller: this, 
)

//also this
await actor.loadFromBundle(rootBundle, filename);
```
The animation didn't load, on loadFromBundle it return "Unable to load asset : PATH"
Its working fine on IOS, please let me know how to get through this

thanks in advance!

**Comment by luigi-rosso** [comment]
Do you have any spaces in your file path? I've noticed that Android sometimes has trouble with this.

**Comment by nizwar** [comment]
Yeah its happened with Android, Flare bundle and asset only work with internal resources, you can't really access flare file outside

but at this moment here is my simple way to get through this
```dart
 return FutureBuilder<Uint8List>(
    future: widget.provider.getMemory(File(fileSnapshot.data)),
    builder: (context, readSnapshot) {
        if (!readSnapshot.hasData) return SizedBox.shrink();
        return FlareActor.memory(
                readSnapshot.data,
                // AssetFlare(bundle: PlatformAssetBundle(), name: snapshot.data.path),
                alignment: Alignment.bottomCenter,
                controller: this,
                fit: BoxFit.cover,
                callback: (r) {},
       );
   },
);
```
