### ISSUE TITLE
Exporting a Certain Part of an Animation & Curved Paths

### ISSUE THREAD

**Issue by yekta** [2d-inc/Flare-Flutter#32]
There should be an option to export a certain part of an animation, no matter where it starts or ends. Like exporting the part that starts from the 4th second to 6th second. This is needed because it allows making loop animation with complex curves to be much much easier, or rather possible. If you always start exporting from the 1st frame, making loops become much harder, sometimes even impossible if they have complex animation curves. Because you would need to repeat some layers certain seconds apart from each other.

Also, any given object should be able to animatable on a curved path, like in After Effects. Drawing the path that a layer would follow is much easier than calculating X and Y values for that to happen.

**Comment by luigi-rosso** [comment]
Hi @yekta,

If you set your work area, we'll only export that region. Is this what you are looking for?
![screen shot 2019-01-18 at 5 30 51 pm](https://user-images.githubusercontent.com/454182/51420447-dd8a4d80-1b46-11e9-96d8-2ae9e995471f.png)

We've been talking internally about the path following feature. There are a few ways to do it. We like the After Effects model but we have some more ideas too. Please voice your opinion on our [roadmap](https://portal.productboard.com/twodimensions/tabs/1-under-consideration) to let us understand which is important to you and why!

Thanks for using Flare.

**Comment by yekta** [comment]
Thanks for fast reply, setting the work area actually did not work for me, that’s why I was very confused how this is not included since it’s a very necessary feature. Do I need to do something special in Flutter to play that section? Because I tried that before and it didn’t work.

On Sat, Jan 19, 2019 at 4:33 AM, Luigi Rosso <notifications@github.com> wrote:
Hi @yekta [https://github.com/yekta] ,

If you set your work area, we'll only export that region. Is this what you are looking for?
[https://user-images.githubusercontent.com/454182/51420447-dd8a4d80-1b46-11e9-96d8-2ae9e995471f.png]

We've been talking internally about the path following feature. There are a few ways to do it. We like the After Effects model but we have some more ideas too. Please voice your opinion on our roadmap [https://portal.productboard.com/twodimensions/tabs/1-under-consideration] to let us understand which is important to you and why!

Thanks for using Flare.

**Comment by yekta** [comment]
Thanks for fast reply, setting the work area actually did not work for me, that’s why I was very confused how this is not included since it’s a very necessary feature. Do I need to do something special in Flutter to play that section? Because I tried that before and it didn’t work.
On Sat, Jan 19, 2019 at 4:35 AM, M. Yekta GÜNGÖR <negoryekta@gmail.com> wrote:
Thanks for fast reply, setting the work area actually did not work for me, that’s why I was very confused how this is not included since it’s a very necessary feature. Do I need to do something special in Flutter to play that section? Because I tried that before and it didn’t work.

On Sat, Jan 19, 2019 at 4:33 AM, Luigi Rosso <notifications@github.com> wrote:
Hi @yekta [https://github.com/yekta] ,

If you set your work area, we'll only export that region. Is this what you are looking for?
[https://user-images.githubusercontent.com/454182/51420447-dd8a4d80-1b46-11e9-96d8-2ae9e995471f.png]

We've been talking internally about the path following feature. There are a few ways to do it. We like the After Effects model but we have some more ideas too. Please voice your opinion on our roadmap [https://portal.productboard.com/twodimensions/tabs/1-under-consideration] to let us understand which is important to you and why!

Thanks for using Flare.

**Comment by luigi-rosso** [comment]
It should just work on its own. Let me do some testing...I think it is something that we updated recently.

**Comment by luigi-rosso** [comment]
I just tried it out and it seems to be working here. Make sure you have the work area toggled on. If you toggle it off, we'll export the whole animation. If you do have it on, send me a link to your Flare file and I can take a look at what's going on.

**Comment by yekta** [comment]
Okay I’ll check it out again an report, I tested it like a week ago so maybe something changed in the meanwhile
On Sat, Jan 19, 2019 at 4:46 AM, Luigi Rosso <notifications@github.com> wrote:
I just tried it out and it seems to be working here. Make sure you have the work area toggled on. If you toggle it off, we'll export the whole animation. If you do have it on, send me a link to your Flare file and I can take a look at what's going on.

**Comment by yekta** [comment]
Loops are still pretty hard to achieve though with complex interpolations, because you can’t save your custom interpolations and apply them to duplicated layer
On Sat, Jan 19, 2019 at 4:46 AM, M. Yekta GÜNGÖR <negoryekta@gmail.com> wrote:
Okay I’ll check it out again an report, I tested it like a week ago so maybe something changed in the meanwhile
On Sat, Jan 19, 2019 at 4:46 AM, Luigi Rosso <notifications@github.com> wrote:
I just tried it out and it seems to be working here. Make sure you have the work area toggled on. If you toggle it off, we'll export the whole animation. If you do have it on, send me a link to your Flare file and I can take a look at what's going on.

**Comment by luigi-rosso** [comment]
We'll be adding presets with the ability to save your own soon, I think that'll help with having a custom set of interpolators. We have a lot do to still, but we more pretty quick :)

**Comment by neurowave** [comment]
You probably need to re-export your file if it was from a week ago! Good point on the interpolation stuff. We have a plan for it already, but as Luigi said, feel free to send us your specific ideas (if you have them) on the roadmap!

**Comment by yekta** [comment]
Awesome :) Can you also add the ability to copy paste a layer in the Animate Section? Because all the keyframes that are attached to a layer would transfer that way. Or just the ability to copy paste all keyframes from one layer to another (if it’s possible). This is very helpful in making loops. If you are wondering why I’m so keen on loops, you can check what I’m doing with them here :D https://loopelf.com and https://banano.fun, we are also almost finished writing a cyptocurrency wallet written in Flutter (waiting for TestFlight approval), in which we use quite a bit of Flare animations https://www.2dimensions.com/a/yekta/files/recent/all On Sat, Jan 19, 2019 at 4:51 AM, Luigi Rosso <notifications@github.com> wrote:
We'll be adding presets with the ability to save your own soon, I think that'll help with having a custom set of interpolators. We have a lot do to still, but we more pretty quick :)

**Comment by yekta** [comment]
Checked, work area in fact worked this time, I should've controlled it one last time before opening the issue :) Thanks for helping.

**Comment by luigi-rosso** [comment]
Don't worry, it's good you did open this issue! Things move fast (it's one of the nice things about having our platform online). We encourage people to file issues as it helps us better understand what specific use cases need better documentation.

**Comment by yekta** [comment]
Hey, sorry to bother you like this, I have a question if you don’t mind. How can I easily sync a Flare animation to a Flutter animation? I thought Flare would take a value like slideAnimation.value, slideAnimation being a Animation<double> but that’s not the case. I couldn’t find how to define a simple controller for the flare animation, like a controller that goes from 0 to 1.

On Sat, Jan 19, 2019 at 9:44 PM, Luigi Rosso <notifications@github.com> wrote:
Closed #32 [https://github.com/2d-inc/Flare-Flutter/issues/32] .
