### ISSUE TITLE
Can't Fork other designs on Flare

### ISSUE THREAD

**Issue by mdanics** [2d-inc/Flare-Flutter#4]
I'm trying to fork a design on Flare, it prompts me for a new file name and once it creates the file the workspace is empty.

Using Chrome on MacOS

**Comment by kimlet** [comment]
same here

**Comment by mdanics** [comment]
Thanks for looking into this. 

Interestingly the preview works, but the editor has no files

**Comment by luigi-rosso** [comment]
We had a bug that was due to a 1 AM migration the day of the presentation. Classic. Should all be good now. Let me know if you run into further issues and thanks so much for testing this out hot off the press!

**Comment by mdanics** [comment]
Haha classic. Yeah it works now (although only for new forks), thanks for fixing it quickly!

I've run into an issue with the preview page being blank, but I'll open an issue in the proper repo
