### ISSUE TITLE
Latest version - NoSuchMethodError: The method '*' was called on null.

### ISSUE THREAD

**Issue by RaviKavaiya** [2d-inc/Flare-Flutter#50]
Hello, I am using the latest version of flare_flutter 1.3.0
Reference code : [https://github.com/tarek360/Boring-Star-Animation](url) (all same, but version 1.3.0)
The code works fine out of the box, but when I changed the animation, it displayed, but a still image (not a moving animation)
And, this was the error : 

`E/flutter (24934): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method '*' was called on null.
E/flutter (24934): Receiver: null
E/flutter (24934): Tried calling: *(0.0)
E/flutter (24934): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (24934): #1      KeyFrameStrokeEnd.setValue (package:flare_dart/animation/keyframe.dart:1161:33)
E/flutter (24934): #2      KeyFrameNumeric.apply (package:flare_dart/animation/keyframe.dart:138:5)
E/flutter (24934): #3      PropertyAnimation.apply (package:flare_dart/animation/actor_animation.dart:199:21)
E/flutter (24934): #4      ComponentAnimation.apply (package:flare_dart/animation/actor_animation.dart:248:27)
E/flutter (24934): #5      ActorAnimation.apply (package:flare_dart/animation/actor_animation.dart:403:26)
E/flutter (24934): #6      FlareActorRenderObject._updateAnimation (package:flare_flutter/flare_actor.dart:468:19)
E/flutter (24934): #7      FlareActorRenderObject.filename=.<anonymous closure> (package:flare_flutter/flare_actor.dart:245:11)
E/flutter (24934): #8      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (24934): #9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (24934): #10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (24934): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (24934): #12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (24934): #13     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (24934): #14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (24934): #15     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
E/flutter (24934): #16     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (24934): #17     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24934): #18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24934): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (24934): #20     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (24934): #21     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24934): #22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24934): #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (24934): #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (24934): #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (24934): `

The animation : 
[https://www.2dimensions.com/a/innocent/files/flare/status_success](url)

EDIT : I used both binary and json formats, but no luck :(

EDIT 2 : I used below animation and is WORKING fine : 
[https://www.2dimensions.com/a/pollux/files/flare/smiley-switch](url)

I don't know what is the problem with my animation :(

**Comment by luigi-rosso** [comment]
Thanks for reporting, I'll look into this today and report back.

**Comment by luigi-rosso** [comment]
I've just pushed an updated flare_flutter 1.3.1 which should fix this issue. Please try it out and let me know!

**Comment by RaviKavaiya** [comment]
Thanks for the update. I will check it as soon as possible as I get free and report back

**Comment by RaviKavaiya** [comment]
@luigi-rosso  I tried the same animation with version 1.3.2. No, the problem is **not** resolved.
I wonder that there must be a problem with my animation. What do you say?

**Comment by umberto-sonnino** [comment]
Hey @RaviKavaiya, we investigated this a bit further and it appears to be a combination of both!
You set your Trim Path keys for the _Check_ shape in your animation, and then you set Trim Path to _Off_ afterwards. 
So you can circumvent the issue right now by setting instead to _Sequential_
We're working on a fix in the meantime!

**Comment by RaviKavaiya** [comment]
@umberto-sonnino OK, I set it to _Sequential_ and it works fine.

**Comment by nurbek-b** [comment]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building HomePage(dirty, state: _HomePageState#6755f):
The method '*' was called on null.
Receiver: null
Tried calling: *(0.85)

The relevant error-causing widget was:
  HomePage file:///Users/macbookpro/Desktop/agro/lib/screens/home/home_screen.dart:17:5
