### ISSUE TITLE
Flare is not exporting correctly in Flutter

### ISSUE THREAD

**Issue by uggyk** [2d-inc/Flare-Flutter#51]
Hello. 

firstly, this is the flare file https://www.2dimensions.com/a/uggy/files/flare/burgersplash-2/preview
secondly, there is a circle there that for some reason does not show in the preview. and when I export it, and put it in flutter, only two of all objects are shown (the bottom bun, and the top closed bun). 

FYI, in the flutter app, it used to work a week ago. perhaps there was an update of some sort? 

this is the code that I have been using:

`
import 'package:flare_flutter/flare_actor.dart';

FlareActor("assets/BurgerSplash 2.flr",
                animation: "new_splash",
                color: Colors.white,
                fit: BoxFit.contain,
                alignment: Alignment.center),`

**Comment by luigi-rosso** [comment]
We did have an update last week, if you exported the file this week, you'll need to update the runtime to the latest package. We're going to get better about detecting this condition and notifying you that you likely need to update the package.

Let me know if that still doesn't work for you, I can do a more in depth investigation with your actual file.

**Comment by uggyk** [comment]
I just changed the package to version ^1.3.0, and the error is still there, please investigate further. I wonder if it's the same error with https://github.com/2d-inc/support/issues/148

**Comment by uggyk** [comment]
fyi, everytime I want to edit the https://www.2dimensions.com/a/uggy/files/flare/burgersplash-2/preview I have to go to the "circle" object and click (tick) on Fill (color) in order for the "circle to appear in the animation and then it would appear.

**Comment by uggyk** [comment]
this is what shows in the app (for the whole lifetime of the widget). I do have another animation showing and it is working flawlessly.

![screenshot_1551965904](https://user-images.githubusercontent.com/45707311/53977097-b224e780-4121-11e9-938a-e7d070eec3bd.png)

**Comment by luigi-rosso** [comment]
Thanks, I'll look into this right now. Will report back soon.

**Comment by luigi-rosso** [comment]
This is what I see right now, could you share your code? 

![image-1](https://user-images.githubusercontent.com/454182/53981861-5a0dc700-40c8-11e9-8269-0a4073cb2d0f.jpg)

**Comment by uggyk** [comment]
did the animation work as expected?

import 'package:flare_flutter/flare_actor.dart';

FlareActor("assets/BurgerSplash 2.flr",
animation: "new_splash",
color: Colors.white,
fit: BoxFit.contain,
alignment: Alignment.center),`

 


this is the code that I have used.

**Comment by luigi-rosso** [comment]
Yes the animation worked correctly, but I was able to break it as in #49 by reloading the file. I've pushed a fix, try package 1.3.1.

**Comment by luigi-rosso** [comment]
Zip file attached with the flr file I used.

[BurgerSplash 2.flr.zip](https://github.com/2d-inc/Flare-Flutter/files/2942986/BurgerSplash.2.flr.zip)

**Comment by uggyk** [comment]
nope, nothing is working. is there any way I could revert back to 11 December version of this? 
https://www.2dimensions.com/a/uggy/files/flare/burgersplash/preview

I feel like you are correct. something is off with the package. I changed the color to black (from white). it showed the whole thing but without the animation. with the animation, everything breaks, and back to square one.

**Comment by uggyk** [comment]
this is the whole code. sorry I had to clean it up.

```
import 'dart:core';
import 'dart:async';
import 'package:change_app/ui/common/constants.dart';
import 'package:flare_flutter/flare_actor.dart';
import 'package:flutter/material.dart';
import 'package:flare_flutter/flare.dart';
import 'package:flare_dart/math/mat2d.dart';
import 'package:flare_flutter/flare_actor.dart';

class SplashScreen extends StatefulWidget {
  final int seconds;
  final Color backgroundColor;
  final dynamic navigateAfterSeconds;
  SplashScreen({
    @required this.seconds,
    this.navigateAfterSeconds,
    this.backgroundColor = Colors.white,
  });

  @override
  _SplashScreenState createState() => _SplashScreenState();

}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();
    Timer(Duration(seconds: widget.seconds), () {
      Navigator.of(context).pushReplacement(
        PageRouteBuilder(
          pageBuilder: (_, __, ___) => widget.navigateAfterSeconds,
          transitionsBuilder: (context, animation, secondaryAnimation, child) =>
              FadeTransition(opacity: animation, child: child),
        ),
      );
    });
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: widget.backgroundColor,
      body: InkWell(
        child: Stack(
         // fit: StackFit.expand,
          children: <Widget>[
            FlareActor("assets/BurgerSplash.flr",
               // animation: "new_splash",
                color: Colors.white10,
                fit: BoxFit.contain,
                alignment: Alignment.center),
            new Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                new Expanded(
                  flex: 2,
                  child: new Container(),
                ),
                Expanded(
                  flex: 2,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      sloganTextAr,
                      Padding(
                        padding: const EdgeInsets.only(top: 20.0),
                      ),
                      sloganTextEn
                    ],
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by uggyk** [comment]
I found the problem. it was the 

''' color: Colors.white10 '''

if I remove that line everything works.

**Comment by luigi-rosso** [comment]
Thanks for the code, I will try it out in a few minutes and see why the color value is causing problems...

**Comment by luigi-rosso** [comment]
I caught the issue with the color override. That should work now too. Version 1.3.2

**Comment by luigi-rosso** [comment]
Let me know if you can confirm it, then we can close the issue! Thanks again for reporting it.

**Comment by uggyk** [comment]
yes it works now, thanks champ!
