### ISSUE TITLE
Flutter - Android Release version gets a weird output

### ISSUE THREAD

**Issue by madtocc** [2d-inc/Flare-Flutter#52]
Hi, I was testing the flare animation for a few weeks and everything works fine, however when I build my app to a release version for Android some parts of the flare gets scrambled like the image below:
![release](https://user-images.githubusercontent.com/12486417/53984124-6d845680-40f7-11e9-9380-8f7ef0555896.png)

The left column show the image that's rendered the first time I open the app. When I scroll the list it seems to show the proper image (right column).

**Comment by luigi-rosso** [comment]
We had a bug that was just fixed with incorrect animations applied on the current Flare file. Could you try this out with 1.3.1 and let me know if you still see the issue? We just published a few minutes ago!

If you still see the issue, would you mind sharing your source?

**Comment by madtocc** [comment]
I have updated to the versiob 1.3.1 but the issue remains when I build the release version (build apk release) :( I'll make a simple flutter app to mimic what my app does and I'll post it here soon. Thanks for your quick reply!

**Comment by luigi-rosso** [comment]
There was an issue like this on a Pixel 2 device if I remember correctly... Any chance you can try the release build on a different device to see if it’s device related?

**Comment by madtocc** [comment]
Hi, I've tried with 3 different devices and it shows the scrambled flare randomly...
In my app the flare is an icon for a device. Initially it runs the animation loading, when it receives the info from the server it shows an animation (on or off). It is in this second step that it gets messed up.
I made a [simple app](https://github.com/madtocc/flare_test) to try to reproduce but it only scrambles if I scroll all the way to the bottom while it is loading, otherwise it loads fine. If you want to check it out (it only shows this behavior when you build the release version --> flutter build apk).

**Comment by RazaGR** [comment]
I have the same issue on iOS device

**Comment by madtocc** [comment]
Hi, I have tried a few modifications on my code and it turns out that the opacity widget has something related to this weird assembly of the flare. The flare shows normally after removing the opacity widget. Hope you can investigate why the opacity does it.

**Comment by luigi-rosso** [comment]
Here's a reference to the bug filed with Flutter:
https://github.com/flutter/flutter/issues/25687

I don't think this is something we can mitigate on our side, although we are still trying to. Please upvote the issue on the Flutter repository.

**Comment by madtocc** [comment]
Today I've tried with the latest version of flutter (channel master, v1.4.11-pre.34) and the issue is solved. Thanks!

**Comment by dvlj** [comment]
I've upgraded to channel dev, v1.4.14, issue still exsits!
