### ISSUE TITLE
Clipping not working

### ISSUE THREAD

**Issue by YAPPDEF** [2d-inc/Flare-Flutter#55]
In the Flare editor clipping works fine. In Flutter not anymore (the whole image is displayed and no clipping applied)

We're using `flare_flutter: ^1.3.2`

**Comment by umberto-sonnino** [comment]
Hey @YAPPDEF! 
What are you clipping, exactly? Would you mind sharing your Flare file?

**Comment by umberto-sonnino** [comment]
We just updated the repo to a `1.3.3`. Let us know if it works now!

**Comment by YAPPDEF** [comment]
Perfect, works just fine. Thank you guys! 🙌
