### ISSUE TITLE
Animation is broken

### ISSUE THREAD

**Issue by AndreiNikitin** [2d-inc/Flare-Flutter#57]
https://ibb.co/5MVDHjB - unexpected result
https://ibb.co/bvpBV1S - normal result

This problem happens when this animation placed in ListView. But I noticed the corruption like that with other animation that placed in the center of the page. Sometimes it works as expected, but 50 % of time it works unexpectedly

I've tested on several devices - the result is the same
Xiaomi Redmi Note 4  android 7.1
Xiaomi Redmi 5A android 7.1
Samsung S7 android 8.0

version of flare - 1.3.2

It happens most of the time in debug build.
Rarely - on release build, but also happens

**Comment by MaximilianKlein** [comment]
we had similar problems. It seemed like this was a skia-Caching problem https://github.com/flutter/flutter/issues/28227 . Those are mostly fixed (at least for us) since Flutter v. 1.4.* . the only problem we still have are vertical lines are not drawn sometimes.

**Comment by AndreiNikitin** [comment]
ok. I will try to upgrade flutter and check again. Will get you know these weekends

**Comment by AndreiNikitin** [comment]
ok. I will try to upgrade flutter and check again. Will get you know these weekends
