### ISSUE TITLE
The animation never start

### ISSUE THREAD

**Issue by fernandolop** [2d-inc/Flare-Flutter#64]
My flare animation never appears. The screen are blank.

Pubspec:
flare_flutter: ^1.3.6

assets: 
 - assets/OpacityLogo.flr

main.dart:
FlareActor("OpacityLogo.flr", alignment:Alignment.center, fit:BoxFit.contain,  animation: "resortesCar"))

Animation: https://www.2dimensions.com/a/Fernando/files/flare/opacitylogo

can anybody help me?

Thanks.
Google translate.

**Comment by umberto-sonnino** [comment]
Hey fernando, thanks for the report!
I've tested your file on this end, but everything seems to be running as expected.

Could you provide more details of your Flutter widget layout?

**Comment by fernandolop** [comment]
Hi Umberto:
This is my code:
return Scaffold(
      appBar: AppBar(
        title: Text("Flare Test"),
        centerTitle: true,
      ),
      body: ListView(
        children: <Widget>[
          Container(
            height: 500,
            child: FlareActor("assets/OpacityLogo.flr",
                alignment: Alignment.center,
                fit: BoxFit.contain,
                animation: "resortesCar"),
          )
        ],
      ),
    );

Thanks for help me!
![image](https://user-images.githubusercontent.com/23640978/55471868-17fd7580-55e1-11e9-9994-db98f028ddef.png)

Thanks for help me!
