### ISSUE TITLE
Animation freezes after navigating using 1.3.7+

### ISSUE THREAD

**Issue by johnyyhign** [2d-inc/Flare-Flutter#68]
Hello! I have some looped animations on some screens in my app, they work when we enter the screen, but if we `push` another route and then `pop` the animation is frozen.
So it looks like this: 
1. SCREEN_WITH_LOOPED_ANIMATION - works
2. `push` another route (with or without an animation, if there is an animation it works fine)
3. `pop` to SCREEN_WITH_LOOPED_ANIMATION - animation doesn't play

I'm using Flutter `master` channel, so ~`1.4.12` and the latest flare pub `1.3.8`, works fine with `1.3.7`
Any idea? Also tested with flutter `beta` and `stable` channel

**Comment by johnyyhign** [comment]
I've tested previous versions `1.3.6` and `1.3.7` and when came back to `1.3.8` it works, seems like some cache was causing the trouble

**Comment by johnyyhign** [comment]
I've tested previous versions `1.3.6` and `1.3.7` and when came back to `1.3.8` it works, seems like some cache was causing the trouble, so I'll reopen if it happens again

**Comment by luigi-rosso** [comment]
Let me know if you run into this again. Definitely sounds suspicious. We did change the render model to use an abstracted render box in the latest version (1.3.8). I'm wondering if you're running into a race condition...

**Comment by johnyyhign** [comment]
It happended again after a while, quickly coming back to previous versions didn't fix it, but i haven't cleared anything so just changed the pubspec and tried again. 
I'll try to find conditions when exactly this is happening, maybe tomorrow I'll have some time and post here more details. Definitely happens on `master` flutter with `1.3.8`

**Comment by johnyyhign** [comment]
Okay, I've tested this once again. And it works fine with `1.3.6` and for higher versions it behaves as explained in the first post. Could you comment on this @luigi-rosso ? Do you need any logs that can help?

**Comment by luigi-rosso** [comment]
I'm going to try to take a look at this today. If you have a source example that shows it clearly, that'd help, otherwise I can try to repro it myself.

**Comment by johnyyhign** [comment]
Thanks @luigi-rosso I'm not close to my PC now, but just place any looped animation, push and pop another screen and it's frozen, so should be easy to repro within 5mins. Thank you!

**Comment by luigi-rosso** [comment]
Just a quick note on this, I have been looking into it and I can repro the issue. There are a couple conditions that are causing this which are related to performance improvements we made (like not rendering when off screen).  I have a fix but now it has exposed another issue where some widgets will re-attach when they are offscreen, so I'm working through that now. I'll keep you updated here as I make progress.

**Comment by luigi-rosso** [comment]
I think I have this solved now. Please give 1.3.10 a try!

**Comment by johnyyhign** [comment]
Seems to be fixed! Thank you so much for fantastic library and quick action!
