### ISSUE TITLE
Flutter animation not same as one in the browser

### ISSUE THREAD

**Issue by milosjovac** [2d-inc/Flare-Flutter#72]
[Animation export](https://github.com/2d-inc/Flare-Flutter/files/3076185/5.flr2d.zip) - Animation is 'Success'

How it looks in a browser:
![browser](https://user-images.githubusercontent.com/2808506/56079993-d8623500-5dfb-11e9-9094-293c109b6e1e.gif)

On a phone there is no animation at all and green circle is missing:
![image](https://user-images.githubusercontent.com/2808506/56080057-5b838b00-5dfc-11e9-84c4-6d79b0613b9e.png)

Flutter code:
```
...
String animation = 'Success';
...
Expanded(
                flex: 3,
                child: FlareActor('assets/animations/inclusion.flr',
                    alignment: Alignment.center,
                    fit: BoxFit.contain,
                    animation: animation),
              ),
```

*Note that 'Animation export' file contains 4 animations in total. All other animations work just fine.

**Comment by neurowave** [comment]
Hi @milosjovac, can you share your Flare file? Also, are you playing this success animation first, or are you playing another animation first? I wonder if one of your other animations is setting a property at the end that causes your success animation to be hidden.

When mixing animations like this, you need to make sure you reset your keys at the start of your animation for anything that might get changed in another.

If you send me a link to your Flare file I can take a look!

**Comment by milosjovac** [comment]
Hi @neurowave, thank you for the response. You can find animation export file in initial comment, but if you prefer link please take a look here https://www.2dimensions.com/a/milosjovac/files/flare/new-file-5 . Animation is shown in following sequence (Idle -> Searching -> Success)

Let me know if you need anything else.

**Comment by neurowave** [comment]
Yeah the direct file is easier for me to work with! Thanks! I'll take a look and let you know.

**Comment by neurowave** [comment]
You are setting your "Checkmark" opacity to 0 in the Idle and Searching animations. You need to set the "Checkmark" node's opacity to 1 at the start of the Success animation.

Try it out, it should fix it.

**Comment by milosjovac** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2808506/56082849-399b0000-5e1e-11e9-901c-8638e14599f8.gif)

Works like a charm. Thanks @neurowave!

**Comment by neurowave** [comment]
Great!
