### ISSUE TITLE
Objects outside the ArtBoard are visible

### ISSUE THREAD

**Issue by optimygmbh** [2d-inc/Flare-Flutter#85]
Is it a setting in Flare or Flutter, that drawing elements only are visible inside the ArtBoard and not outside?

For example I'm having an animation with clouds flying from left to right. They start at left outside the ArtBoard and end right outside of the ArtBoard. But I can see the clouds "waiting" in the Flutter App. And how you can see the sun is visible as well outside the ArtBoard:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/44826660/57216269-fbaa8980-7021-11e9-9040-60457297adde.png">

**Comment by umberto-sonnino** [comment]
Did you enable "Clip Contents" for the Artboard in your Flare file?
There's an option for that in the Selection Panel:
![Artboard Clipping](https://i.imgur.com/bp3jpSz.png)

**Comment by optimygmbh** [comment]
Yes I enabled "Clip Contents" in the Artboard of my Flare file. 

Now I thought maybe I overwrite it in Flutter in the Flutter Actor Artboard. But there  clipContents is set to true as well:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/44826660/57346718-36c3ce80-7182-11e9-9bef-b8a1121ba209.png">

This is my Flare file: https://www.2dimensions.com/a/optimygmbh/files/flare/hollywood/embed.

**Comment by jcairo** [comment]
Any updates on this? I have the exact same problem.

**Comment by umberto-sonnino** [comment]
Hey @jcairo, I've tested your file locally and I don't see the issue on my side.
Could you share a more complete example with your widget layout where this is happening?

**Comment by jcairo** [comment]
Hey Umberto. Not sure how much you want here. I've added the code for the widget where the problem is. I can also provide you with a Flutter repo if that is easier?

`class PlayButton extends StatefulWidget {
  final Player player;
  const PlayButton({
    Key key,
    this.player,
  }) : super(key: key);

  @override
  _PlayButtonState createState() => _PlayButtonState();
}

class _PlayButtonState extends State<PlayButton> with TickerProviderStateMixin {
  String _animationName = "PlayToPause";
  @override
  Widget build(BuildContext context) {
    return Container(
        decoration: BoxDecoration(border: Border.all(color: Colors.black)),
        height: 100,
        width: 100,
        child: FlatButton(
          child: FlareActor(
            "assets/animations/anim.flr",
            fit: BoxFit.fill,
            animation: _animationName,
            sizeFromArtboard: true,
          ),
          onPressed: () {
            var tempName;
            if (_animationName == "PlayToPause") {
               tempName = "PauseToPlay";
            } else {
              tempName = "PlayToPause";
            }

            setState(() {
              _animationName = tempName;
            });
          },
        ));

    return IconButton(
      onPressed: widget.player.fileIsLoaded ? () => widget.player.play() : null,
      icon: Icon(
        FontAwesomeIcons.playCircle,
        color: Colors.black,
      ),
      iconSize: kIconSize,
    );
  }
}
`

**Comment by umberto-sonnino** [comment]
With your file above and [this configuration](https://gist.github.com/umberto-sonnino/53afc897db64cff3598f91278a158fe0), everything still looks fine on my side.

**Comment by luigi-rosso** [comment]
It looks like the Flare runtime may not be applying the final frame of the animation. Is the behavior consistent amongst re-runs or is it always at a slightly different spot? Does the behavior change in release/debug mode?

**Comment by jcairo** [comment]
Hey Luigi,

I've now tried in release mode and i'm still seeing the same problem. 

I don't think it's just the final frame. Using this animation
[animatiion](https://www.2dimensions.com/a/jonnyc/files/flare/play-pause) I'm seeing way way outside the artboard.

Artboard in Flare shows
![Screen Shot 2019-08-25 at 11 28 55 AM](https://user-images.githubusercontent.com/4959155/63653561-9d69f980-c72b-11e9-9eaf-5cc33dac03c1.png)

Flare actor in Flutter shows.
![Screen Shot 2019-08-25 at 11 36 17 AM](https://user-images.githubusercontent.com/4959155/63653628-955e8980-c72c-11e9-88ba-a0db88e7d307.png)

Same code as above but with boxfit.contain
```dart
class PlayButton extends StatefulWidget {
  final Player player;
  const PlayButton({
    Key key,
    this.player,
  }) : super(key: key);

  @override
  _PlayButtonState createState() => _PlayButtonState();
}

class _PlayButtonState extends State<PlayButton> with TickerProviderStateMixin {
  String _animationName = "PlayToPause";
  @override
  Widget build(BuildContext context) {
    return Container(
        decoration: BoxDecoration(border: Border.all(color: Colors.black)),
        height: 100,
        width: 100,
        child: FlatButton(
          child: FlareActor(
            "assets/animations/PlayPause.flr",
            fit: BoxFit.contain,
            animation: _animationName,
            sizeFromArtboard: true,
          ),
          onPressed: () {
            var tempName;
            if (_animationName == "PlayToPause") {
               tempName = "PauseToPlay";
            } else {
              tempName = "PlayToPause";
            }

            setState(() {
              _animationName = tempName;
            });
          },
        ));
  }
}

```

**Comment by umberto-sonnino** [comment]
Hey @jcairo, thanks a lot for your last example! We were finally able to reproduce the problem and found the bug.

We published a new version of the package which should now behave correctly; you can find it [here](https://pub.dev/packages/flare_flutter/versions/1.5.7)!
