### ISSUE TITLE
Animation controller seems to be lost in reorderable list view

### ISSUE THREAD

**Issue by AndreiNikitin** [2d-inc/Flare-Flutter#88]
The problem appears if there is FlareActor Widget in the item widget hierarchy and in the dragging process. Looks like controller is lost somewhere, because the animation artboard is reseted to the default and no animation is happening. Or maybe the problem somewhere in my controller code. 
Code example:
https://gist.github.com/AndreiNikitin/62f3533e908d5711aa0271866b62014c
The animation, which I used in this example:
https://www.2dimensions.com/a/andriy07/files/flare/new-file-2
A video that describes the problem:
https://youtu.be/Mnjb5zRe4Bg

**Comment by umberto-sonnino** [comment]
Hey @AndreiNikitin, your gist and youtube video don't seem to be accessible, could you make them available so we can take a look?

**Comment by AndreiNikitin** [comment]
@umberto-sonnino 
Check video now.
Here is code example
https://gist.github.com/AndreiNikitin/aac02845b6926255e51b32e99b17c9cc

**Comment by umberto-sonnino** [comment]
Thanks for the update, but your gist doesn't build, so I can't reproduce the issue. Would you mind providing a full working example?

**Comment by AndreiNikitin** [comment]
During creating test project for you I investigated that this behaviour depends on environment sdk version
This bug occurs on
 `environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"`
I changed it to 
`
 sdk: ">=2.1.0 <3.0.0"`
And everything works as expected. Thank you for your time

**Comment by umberto-sonnino** [comment]
No problem, glad this is working!
