### ISSUE TITLE
Flare animations not visible in release/profile build mode

### ISSUE THREAD

**Issue by grandpa-guru** [2d-inc/Flare-Flutter#92]
Hi all,

I'm having a problem where **some** Flare animations are invisible in release or profile mode.

[This one is visible](https://www.2dimensions.com/a/pollux/files/flare/success-check/preview)
[This one is invisible](https://www.2dimensions.com/a/aalibegic/files/flare/slidinsquaresloader/preview)

I really don't know what to do in this situation. Maybe the squares loader animations is wrong in some way?

---

I'm using **flare_flutter: ^1.5.0**.

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-GB)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\Anis\Programs\flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Anis\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[√] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.0

[√] Connected device (1 available)
    • ANE LX1 • 9WV4C19131006232 • android-arm64 • Android 8.0.0 (API 26)

Anybody knows why this occurs?

**Comment by luigi-rosso** [comment]
It's an issue with v1.5.4-hotfix.2, if you upgrade to something newer you'll see it's gone. It's unfortunate that it's the current stable build.

**Comment by grandpa-guru** [comment]
I tried changing to master channel but there was a breaking change https://github.com/flutter/flutter/issues/31962 and half of my packages are failing to build... any other way?

**Comment by luigi-rosso** [comment]
There's a breaking change on both dev and master with one of the APIs that Flare uses. Unfortunately we have to keep the version on pub compatible with stable. To use a more bleeding edge version, point your pubspec to our github:

```
flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    ref: dev
    path: flare_flutter
```

Just be aware that dev is a moving target, if you want to be keep it compatible with a specific version of master you are on, reference the current dev tree instead:

```
flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    ref: c51192dec50dec034d121f6aad7d2e8733c7e279
    path: flare_flutter
```

**Comment by luigi-rosso** [comment]
That'll allow Flare to work with newer Flutter versions, you may need to do something similar for the other packages.

**Comment by grandpa-guru** [comment]
I got stuck on https://github.com/AndreHaueisen/flushbar/issues/44#issuecomment-485756864. But, why some of the animations are working correctly?

**Comment by grandpa-guru** [comment]
Changed Flutter channel to master and version 1.5.9, changed the source of the flare_flutter to GitHub instead of pub.dev, fixed errors in other packages, successfully built the app... still no animations.

**Comment by luigi-rosso** [comment]
That's frustrating, sorry for the trouble. Lots of things changed this week so quite a few of them are still settling. 

Are you seeing no animations in release/profile or no animations in debug as well?

**Comment by grandpa-guru** [comment]
I have two animations side by side. The one your brother [made](https://www.2dimensions.com/a/pollux/files/flare/success-check/preview) and the one I [made](https://www.2dimensions.com/a/aalibegic/files/flare/slidinsquaresloader/preview). When I run my application in the debug mode I can see both animations but in the release/profile mode all I can see is your brother's animation.

**Comment by luigi-rosso** [comment]
It really sounds like this issue: https://github.com/2d-inc/Flare-Flutter/issues/87

I thought this had been fixed right after hotfix.2, but it sounds like it's still a problem. It sounds like flutter 1.2.1 with flare_flutter 1.5.0 (from pub) should work together. In the meantime I'll make sure we open an issue with the main flutter repository too.

**Comment by annalaufey** [comment]
I'm having the same problem. 
I am currently on  Flutter version 1.5.4-hotfix.2 and flare_flutter: ^1.5.0 and my animation is not showing in release mode, only in debug mode.

**Comment by luigi-rosso** [comment]
Can the people who were able to reproduce this issue please give it a try on the latest flutter master or dev channel? You'll need to point your pubspec to our flare dev:

```
flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    ref: dev
    path: flare_flutter
```

**Comment by grandpa-guru** [comment]
Confirmed that animations are working in release/profile mode while using `Flutter 1.7.6-pre.41 • channel master` and `flare_flutter git:dev'.
