### ISSUE TITLE
Compatibility with Flutter 1.5 and Dart 2.2.0

### ISSUE THREAD

**Issue by AbdoXLabs** [2d-inc/Flare-Flutter#94]
`file:///Users/USER/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.0/lib/flare.dart:1028:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);`

**Comment by umberto-sonnino** [comment]
Hey @AbdoXLabs the problem you're seeing has been reported a few times already, and it's related to some breaking changes in the Flutter API. 
We're currently providing our users with some different branches that should accomodate everyone's needs.
From what I'm seeing on your error report, you should be able to use either the `master` or `dev` branch to fix your issue.

**Comment by AbdoXLabs** [comment]
**Thank you @umberto-sonnino  for your answer !**
Can you give me an example of how I can I use the `master` or `dev` branch.
I tried this in my `pubspec.yaml` but it doesn't work:
`flare_flutter:`
  `git:`
      `url: 'https://github.com/2d-inc/Flare-Flutter.git'`
      `path: 'flare_flutter'`

It gives me this error :
`
Invalid description in the "flare_flutter" pubspec on the "flare_dart" dependency: "../flare_dart" is a relative path, but this isn't a local pubspec.
`

**Comment by umberto-sonnino** [comment]
You should our README's directions. In your `pubspec.yaml`
```flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    ref: dev
    path: flare_flutter```

This'll target the `dev` branch. You can find more details on [flutter.dev](https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages)

**Comment by umberto-sonnino** [comment]
I will also close this issue since the problem as been fixed. 
Please refer to the [README](https://github.com/2d-inc/Flare-Flutter/blob/3a6d42f772b8db6d58155081e1f35cecd6f829c1/README.md#flutter-channel) for details.
