### ISSUE TITLE
FlareActor missing half of the picture

### ISSUE THREAD

**Issue by fengqiangboy** [2d-inc/Flare-Flutter#95]
I have create a flare , it is here: [https://www.2dimensions.com/a/fengqiangboy/files/flare/scan](https://www.2dimensions.com/a/fengqiangboy/files/flare/scan).

it looks like 

![image](https://user-images.githubusercontent.com/13598763/58242527-8fe65180-7d81-11e9-9dd0-2b58a8af9753.png)

But when I use it in flutter, it miss half of cycle

![image](https://user-images.githubusercontent.com/13598763/58242612-b4422e00-7d81-11e9-9d66-51e3bdfd3528.png)

I have create a demo project at: [https://github.com/fengqiangboy/scan_flare](https://github.com/fengqiangboy/scan_flare)

**Comment by Antoniozinchenko** [comment]
Have the same issue with stroke offset property

**Comment by umberto-sonnino** [comment]
We caught an issue with our trim path logic, and it should be fixed with the latest commit on `master`.
I've tested your file locally and it seems to be rendering the whole path correctly now!
