### ISSUE TITLE
Please clarify if Flare itself is open source, if one can run Flare locally, or if Flare is only an online SAAS. I see no option for downloading Flare itself...

### ISSUE THREAD

**Issue by vectorselector** [2d-inc/Flare-Flutter#97]
Can anyone please clarify if Flare itself is open source, if one can run Flare locally, or if Flare is only an online SAAS. I see no option for downloading Flare itself...

I understand that Flare runtimes have been built for Flutter, Dart, JS, etc.
I am referring to the designing application itself.

**Comment by luigi-rosso** [comment]
The Flare app itself is currently closed source. We've discussed open sourcing it, but it's currently not a viable model for us. We'd love to hear the community's thoughts on it.

**Comment by luigi-rosso** [comment]
I'm closing this as I believe the question has been answered, feel free to re-open if you have further questions about this @vectorselector.
